/**
 * Minimal Markdown → HTML converter for AI-generated study summaries.
 * Handles the exact patterns the study-ai system prompt produces:
 * ##/### headers, **bold**, *italic*, `code`, - bullet lists.
 * Output is injected via dangerouslySetInnerHTML — content is trusted
 * (generated by our own AI system prompt, never raw user HTML).
 */

function inlineFormat(text: string): string {
  return text
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g,     '<em>$1</em>')
    .replace(/`(.+?)`/g,       '<code>$1</code>')
}

export function markdownToHtml(md: string): string {
  if (!md.trim()) return ''

  // Escape HTML in raw source before any pattern substitution
  const safe = md
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')

  const lines  = safe.split('\n')
  const output: string[] = []
  let inList   = false

  const closeList = () => {
    if (inList) { output.push('</ul>'); inList = false }
  }

  for (const line of lines) {
    const t = line.trim()

    if (!t) {
      closeList()
      continue
    }

    if (t.startsWith('### ')) {
      closeList()
      output.push(`<h4>${inlineFormat(t.slice(4))}</h4>`)
    } else if (t.startsWith('## ')) {
      closeList()
      output.push(`<h3>${inlineFormat(t.slice(3))}</h3>`)
    } else if (t.startsWith('# ')) {
      closeList()
      output.push(`<h2>${inlineFormat(t.slice(2))}</h2>`)
    } else if (/^[-*] /.test(t)) {
      if (!inList) { output.push('<ul>'); inList = true }
      output.push(`<li>${inlineFormat(t.slice(2))}</li>`)
    } else if (/^\d+\. /.test(t)) {
      // Numbered list item — render as unordered for visual consistency
      if (!inList) { output.push('<ul>'); inList = true }
      output.push(`<li>${inlineFormat(t.replace(/^\d+\. /, ''))}</li>`)
    } else {
      closeList()
      output.push(`<p>${inlineFormat(t)}</p>`)
    }
  }

  closeList()
  return output.join('\n')
}
