/**
 * utils/recipeLibrary.ts — Built-in Recipe Library
 *
 * A large catalogue of basic, everyday recipes with full data:
 * ingredients, calories, macros (protein/carbs/fat), estimated cost
 * per serving, cook time, equipment tier, dietary tags, and a tip.
 *
 * Powers:
 *   • The browsable Recipe Library in the Recipes & Resources tab
 *   • The smart Week-Plan generator (calorie / protein / budget aware)
 *
 * Costs and calories are stored PER SERVING (already divided down),
 * so the generator can sum them directly without unit math.
 */

import type { EquipmentTier, MealTypeKey } from './mealData'

export interface LibraryRecipe {
  id:          string
  name:        string
  mealType:    MealTypeKey          // breakfast | lunch | dinner
  categories:  string[]             // subset of RECIPE_CATEGORIES (browse filter)
  equipment:   EquipmentTier[]      // tiers that can make it
  cookMinutes: number
  cost:        number               // USD per serving
  calories:    number               // kcal per serving
  protein:     number               // g per serving
  carbs:       number               // g per serving
  fat:         number               // g per serving
  ingredients: string[]
  dietaryTags: string[]
  tips:        string
}

/* Shorthands for equipment combos to keep the dataset compact */
const ANY:  EquipmentTier[] = ['no_kitchen', 'microwave', 'mini_fridge', 'hot_plate']
const MICRO: EquipmentTier[] = ['microwave', 'mini_fridge', 'hot_plate']
const FRIDGE: EquipmentTier[] = ['mini_fridge', 'hot_plate']
const STOVE: EquipmentTier[] = ['hot_plate']

export const RECIPE_LIBRARY: LibraryRecipe[] = [
  /* ════════════════ BREAKFAST ════════════════ */
  { id: 'bk-scrambled-eggs', name: 'Classic Scrambled Eggs', mealType: 'breakfast', categories: ['Breakfast', 'Quick & Easy', 'High Protein', 'Vegetarian'], equipment: STOVE, cookMinutes: 8, cost: 0.90, calories: 220, protein: 14, carbs: 2, fat: 16, ingredients: ['Eggs', 'Butter', 'Salt'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Low heat, stir constantly, pull off just before fully set.' },
  { id: 'bk-mug-eggs', name: 'Microwave Mug Eggs', mealType: 'breakfast', categories: ['Breakfast', 'College Dorm', 'Quick & Easy', 'High Protein', 'Vegetarian'], equipment: MICRO, cookMinutes: 3, cost: 1.00, calories: 230, protein: 16, carbs: 3, fat: 15, ingredients: ['Eggs', 'Milk', 'Cheese (shredded)', 'Salt'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free', 'high-protein'], tips: '30s, stir, 30s more so it does not overflow.' },
  { id: 'bk-overnight-oats', name: 'Overnight Oats', mealType: 'breakfast', categories: ['Breakfast', 'Meal Prep', 'Budget Friendly', 'Vegetarian'], equipment: FRIDGE, cookMinutes: 5, cost: 0.90, calories: 350, protein: 12, carbs: 55, fat: 9, ingredients: ['Oatmeal', 'Milk', 'Banana'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Mix in a jar at night, eat cold in the morning.' },
  { id: 'bk-pb-oats', name: 'Peanut Butter Oats', mealType: 'breakfast', categories: ['Breakfast', 'High Protein', 'Vegetarian'], equipment: MICRO, cookMinutes: 4, cost: 1.10, calories: 440, protein: 16, carbs: 56, fat: 18, ingredients: ['Oatmeal', 'Milk', 'Peanut butter', 'Banana'], dietaryTags: ['vegetarian'], tips: 'Stir peanut butter in while the oats are hot.' },
  { id: 'bk-yogurt-parfait', name: 'Yogurt Parfait', mealType: 'breakfast', categories: ['Breakfast', 'Quick & Easy', 'High Protein', 'Vegetarian'], equipment: ANY, cookMinutes: 3, cost: 1.80, calories: 280, protein: 18, carbs: 38, fat: 6, ingredients: ['Greek yogurt', 'Granola bar', 'Banana'], dietaryTags: ['vegetarian', 'gluten-free', 'high-protein'], tips: 'Layer yogurt, crushed granola, and fruit.' },
  { id: 'bk-avocado-toast', name: 'Avocado Toast', mealType: 'breakfast', categories: ['Breakfast', 'Quick & Easy', 'Vegetarian'], equipment: STOVE, cookMinutes: 7, cost: 1.70, calories: 320, protein: 8, carbs: 34, fat: 18, ingredients: ['Bread (loaf)', 'Avocado', 'Salt', 'Hot sauce'], dietaryTags: ['vegetarian', 'dairy-free', 'nut-free'], tips: 'Mash avocado with salt and a squeeze of lemon if you have it.' },
  { id: 'bk-avocado-egg-toast', name: 'Avocado & Egg Toast', mealType: 'breakfast', categories: ['Breakfast', 'High Protein', 'Vegetarian'], equipment: STOVE, cookMinutes: 9, cost: 2.20, calories: 430, protein: 17, carbs: 35, fat: 25, ingredients: ['Bread (loaf)', 'Avocado', 'Eggs', 'Salt'], dietaryTags: ['vegetarian', 'dairy-free', 'nut-free', 'high-protein'], tips: 'Fry or poach the egg and lay it over the mashed avocado.' },
  { id: 'bk-pb-banana-wrap', name: 'PB & Banana Wrap', mealType: 'breakfast', categories: ['Breakfast', 'College Dorm', 'Budget Friendly', 'Vegetarian'], equipment: ANY, cookMinutes: 3, cost: 1.10, calories: 420, protein: 12, carbs: 58, fat: 16, ingredients: ['Tortillas', 'Peanut butter', 'Banana'], dietaryTags: ['vegetarian', 'dairy-free', 'vegan'], tips: 'Spread, add banana, roll. No heat needed.' },
  { id: 'bk-cereal', name: 'Cereal & Milk', mealType: 'breakfast', categories: ['Breakfast', 'College Dorm', 'Quick & Easy', 'Budget Friendly', 'Vegetarian'], equipment: FRIDGE, cookMinutes: 2, cost: 0.70, calories: 270, protein: 8, carbs: 50, fat: 5, ingredients: ['Cereal', 'Milk'], dietaryTags: ['vegetarian'], tips: 'The dorm classic. Add banana for extra calories.' },
  { id: 'bk-banana-pancakes', name: '2-Ingredient Banana Pancakes', mealType: 'breakfast', categories: ['Breakfast', 'Quick & Easy', 'Vegetarian', 'High Protein'], equipment: STOVE, cookMinutes: 12, cost: 1.20, calories: 300, protein: 14, carbs: 30, fat: 13, ingredients: ['Banana', 'Eggs'], dietaryTags: ['vegetarian', 'gluten-free', 'dairy-free', 'nut-free', 'high-protein'], tips: 'Mash banana, whisk with eggs, cook small pancakes.' },
  { id: 'bk-french-toast', name: 'French Toast', mealType: 'breakfast', categories: ['Breakfast', 'Vegetarian'], equipment: STOVE, cookMinutes: 12, cost: 1.40, calories: 360, protein: 13, carbs: 42, fat: 14, ingredients: ['Bread (loaf)', 'Eggs', 'Milk', 'Butter'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Soak bread in egg-milk, fry in butter until golden.' },
  { id: 'bk-breakfast-burrito', name: 'Breakfast Burrito', mealType: 'breakfast', categories: ['Breakfast', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 12, cost: 2.40, calories: 480, protein: 24, carbs: 40, fat: 24, ingredients: ['Tortillas', 'Eggs', 'Cheese (shredded)', 'Canned black beans', 'Hot sauce'], dietaryTags: ['vegetarian', 'nut-free', 'high-protein'], tips: 'Wrap in foil; freezes well for grab-and-go.' },
  { id: 'bk-omelette', name: 'Cheese & Veggie Omelette', mealType: 'breakfast', categories: ['Breakfast', 'High Protein', 'Vegetarian'], equipment: STOVE, cookMinutes: 10, cost: 2.10, calories: 340, protein: 22, carbs: 6, fat: 25, ingredients: ['Eggs', 'Cheese (shredded)', 'Bell pepper', 'Onion', 'Butter'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Cook eggs gently, add fillings to one half, fold over.' },
  { id: 'bk-microwave-oatmeal', name: 'Microwave Oatmeal', mealType: 'breakfast', categories: ['Breakfast', 'College Dorm', 'Quick & Easy', 'Budget Friendly', 'Vegetarian'], equipment: MICRO, cookMinutes: 4, cost: 0.80, calories: 300, protein: 9, carbs: 50, fat: 6, ingredients: ['Oatmeal', 'Milk', 'Banana'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Watch it — oatmeal boils over fast in the microwave.' },
  { id: 'bk-cottage-cheese-bowl', name: 'Cottage Cheese & Fruit Bowl', mealType: 'breakfast', categories: ['Breakfast', 'Quick & Easy', 'High Protein', 'Vegetarian'], equipment: ANY, cookMinutes: 2, cost: 1.60, calories: 240, protein: 24, carbs: 18, fat: 6, ingredients: ['Cottage cheese', 'Banana', 'Granola bar'], dietaryTags: ['vegetarian', 'gluten-free', 'high-protein', 'low-cal'], tips: 'Top cottage cheese with fruit and a crushed granola bar.' },
  { id: 'bk-egg-cheese-sandwich', name: 'Egg & Cheese Sandwich', mealType: 'breakfast', categories: ['Breakfast', 'Quick & Easy', 'High Protein'], equipment: STOVE, cookMinutes: 8, cost: 1.60, calories: 410, protein: 21, carbs: 30, fat: 22, ingredients: ['Bread (loaf)', 'Eggs', 'Cheese (shredded)', 'Butter'], dietaryTags: ['vegetarian', 'nut-free', 'high-protein'], tips: 'Fry the egg hard so it stacks neatly.' },
  { id: 'bk-smoothie', name: 'Banana Berry Smoothie', mealType: 'breakfast', categories: ['Breakfast', 'Quick & Easy', 'Vegetarian', 'High Protein'], equipment: FRIDGE, cookMinutes: 4, cost: 1.90, calories: 300, protein: 18, carbs: 45, fat: 5, ingredients: ['Banana', 'Greek yogurt', 'Milk', 'Peanut butter'], dietaryTags: ['vegetarian', 'gluten-free'], tips: 'Frozen banana makes it thick and cold without ice.' },
  { id: 'bk-toast-jam', name: 'Toast with Butter & Jam', mealType: 'breakfast', categories: ['Breakfast', 'Budget Friendly', 'Quick & Easy', 'Vegetarian'], equipment: STOVE, cookMinutes: 4, cost: 0.50, calories: 250, protein: 5, carbs: 42, fat: 7, ingredients: ['Bread (loaf)', 'Butter', 'Jelly'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Fastest warm breakfast there is.' },
  { id: 'bk-bagel-cream-cheese', name: 'Bagel with Cream Cheese', mealType: 'breakfast', categories: ['Breakfast', 'Quick & Easy', 'Vegetarian'], equipment: ANY, cookMinutes: 4, cost: 1.30, calories: 380, protein: 11, carbs: 52, fat: 14, ingredients: ['Bread (loaf)', 'Cream cheese'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Toast first for the best texture.' },
  { id: 'bk-egg-muffins', name: 'Baked Egg Muffins', mealType: 'breakfast', categories: ['Breakfast', 'Meal Prep', 'High Protein', 'Vegetarian'], equipment: STOVE, cookMinutes: 22, cost: 1.50, calories: 200, protein: 16, carbs: 4, fat: 13, ingredients: ['Eggs', 'Cheese (shredded)', 'Spinach', 'Bell pepper'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free', 'high-protein', 'low-cal'], tips: 'Bake a batch in a toaster oven; reheat all week.' },
  { id: 'bk-protein-shake', name: 'Quick Protein Shake', mealType: 'breakfast', categories: ['Breakfast', 'Quick & Easy', 'High Protein'], equipment: ANY, cookMinutes: 2, cost: 1.40, calories: 260, protein: 28, carbs: 20, fat: 6, ingredients: ['Milk', 'Peanut butter', 'Banana'], dietaryTags: ['vegetarian', 'gluten-free', 'high-protein'], tips: 'Add a scoop of protein powder if you keep some.' },
  { id: 'bk-hard-boiled-eggs', name: 'Hard-Boiled Eggs & Toast', mealType: 'breakfast', categories: ['Breakfast', 'Meal Prep', 'High Protein', 'Budget Friendly'], equipment: STOVE, cookMinutes: 14, cost: 1.00, calories: 290, protein: 18, carbs: 26, fat: 12, ingredients: ['Eggs', 'Bread (loaf)', 'Salt'], dietaryTags: ['vegetarian', 'dairy-free', 'nut-free', 'high-protein'], tips: 'Boil a half-dozen at once and peel as you go.' },
  { id: 'bk-fruit-pb', name: 'Apple & Peanut Butter', mealType: 'breakfast', categories: ['Breakfast', 'Snacks', 'Quick & Easy', 'Budget Friendly', 'Vegetarian'], equipment: ANY, cookMinutes: 2, cost: 1.00, calories: 280, protein: 8, carbs: 32, fat: 16, ingredients: ['Apple', 'Peanut butter'], dietaryTags: ['vegetarian', 'gluten-free', 'dairy-free', 'vegan'], tips: 'Slice the apple and dip. Travels well to class.' },
  { id: 'bk-tofu-scramble', name: 'Tofu Scramble', mealType: 'breakfast', categories: ['Breakfast', 'Vegetarian', 'High Protein'], equipment: STOVE, cookMinutes: 12, cost: 1.80, calories: 250, protein: 20, carbs: 10, fat: 15, ingredients: ['Tofu', 'Spinach', 'Bell pepper', 'Soy sauce', 'Vegetable oil'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'high-protein', 'low-cal'], tips: 'Crumble firm tofu and cook like scrambled eggs.' },
  { id: 'bk-granola-yogurt-pb', name: 'High-Protein Yogurt Bowl', mealType: 'breakfast', categories: ['Breakfast', 'High Protein', 'Vegetarian', 'Meal Prep'], equipment: ANY, cookMinutes: 3, cost: 2.00, calories: 360, protein: 28, carbs: 34, fat: 12, ingredients: ['Greek yogurt', 'Peanut butter', 'Banana', 'Oatmeal'], dietaryTags: ['vegetarian', 'high-protein'], tips: 'Greek yogurt plus PB pushes the protein over 25g.' },

  /* ════════════════ LUNCH ════════════════ */
  { id: 'ln-turkey-sandwich', name: 'Turkey & Cheese Sandwich', mealType: 'lunch', categories: ['Lunch', 'Quick & Easy', 'College Dorm', 'High Protein'], equipment: ANY, cookMinutes: 4, cost: 2.40, calories: 430, protein: 26, carbs: 38, fat: 18, ingredients: ['Bread (loaf)', 'Deli turkey', 'Cheese (shredded)', 'Mayonnaise'], dietaryTags: ['nut-free', 'high-protein'], tips: 'Add lettuce and tomato if you have them.' },
  { id: 'ln-pbj', name: 'Peanut Butter & Jelly', mealType: 'lunch', categories: ['Lunch', 'Budget Friendly', 'Quick & Easy', 'College Dorm', 'Vegetarian'], equipment: ANY, cookMinutes: 3, cost: 0.60, calories: 380, protein: 12, carbs: 50, fat: 16, ingredients: ['Bread (loaf)', 'Peanut butter', 'Jelly'], dietaryTags: ['vegetarian', 'dairy-free'], tips: 'The cheapest reliable lunch on campus.' },
  { id: 'ln-tuna-sandwich', name: 'Tuna Salad Sandwich', mealType: 'lunch', categories: ['Lunch', 'High Protein', 'Budget Friendly', 'Quick & Easy'], equipment: ANY, cookMinutes: 6, cost: 2.00, calories: 400, protein: 28, carbs: 34, fat: 16, ingredients: ['Canned tuna', 'Mayonnaise', 'Bread (loaf)'], dietaryTags: ['nut-free', 'high-protein'], tips: 'Mix tuna with mayo and pepper; spread thick.' },
  { id: 'ln-upgraded-ramen', name: 'Upgraded Ramen Bowl', mealType: 'lunch', categories: ['Lunch', 'College Dorm', 'Budget Friendly', 'High Protein'], equipment: MICRO, cookMinutes: 6, cost: 1.50, calories: 450, protein: 18, carbs: 55, fat: 16, ingredients: ['Ramen noodles', 'Eggs', 'Spinach', 'Soy sauce'], dietaryTags: ['dairy-free', 'nut-free'], tips: 'Crack an egg in halfway through cooking.' },
  { id: 'ln-quesadilla', name: 'Cheese Quesadilla', mealType: 'lunch', categories: ['Lunch', 'Quick & Easy', 'College Dorm', 'Vegetarian'], equipment: STOVE, cookMinutes: 8, cost: 1.80, calories: 420, protein: 16, carbs: 38, fat: 22, ingredients: ['Tortillas', 'Cheese (shredded)', 'Butter'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Crisp both sides in a buttered pan, slice into wedges.' },
  { id: 'ln-bean-quesadilla', name: 'Bean & Cheese Quesadilla', mealType: 'lunch', categories: ['Lunch', 'Budget Friendly', 'Vegetarian', 'High Protein'], equipment: STOVE, cookMinutes: 9, cost: 1.90, calories: 470, protein: 20, carbs: 50, fat: 20, ingredients: ['Tortillas', 'Canned black beans', 'Cheese (shredded)', 'Hot sauce'], dietaryTags: ['vegetarian', 'nut-free', 'high-protein'], tips: 'Mash the beans so the quesadilla holds together.' },
  { id: 'ln-microwave-mac', name: 'Microwave Mac & Cheese', mealType: 'lunch', categories: ['Lunch', 'College Dorm', 'Quick & Easy', 'Budget Friendly', 'Vegetarian'], equipment: MICRO, cookMinutes: 8, cost: 1.50, calories: 430, protein: 12, carbs: 60, fat: 15, ingredients: ['Mac & cheese (box)', 'Milk', 'Butter'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'A splash of milk makes the sauce creamier.' },
  { id: 'ln-burrito-bowl', name: 'Burrito Bowl', mealType: 'lunch', categories: ['Lunch', 'College Dorm', 'High Protein'], equipment: MICRO, cookMinutes: 8, cost: 2.50, calories: 490, protein: 22, carbs: 60, fat: 16, ingredients: ['White rice', 'Canned black beans', 'Cheese (shredded)', 'Hot sauce'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Rice, beans, cheese, salsa — layer in a bowl.' },
  { id: 'ln-grilled-cheese', name: 'Grilled Cheese', mealType: 'lunch', categories: ['Lunch', 'Quick & Easy', 'Budget Friendly', 'College Dorm', 'Vegetarian'], equipment: STOVE, cookMinutes: 7, cost: 1.20, calories: 400, protein: 14, carbs: 34, fat: 24, ingredients: ['Bread (loaf)', 'Cheese (shredded)', 'Butter'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Low-medium heat so the cheese melts before the bread burns.' },
  { id: 'ln-chicken-wrap', name: 'Chicken Caesar Wrap', mealType: 'lunch', categories: ['Lunch', 'High Protein', 'Quick & Easy'], equipment: STOVE, cookMinutes: 12, cost: 3.00, calories: 480, protein: 34, carbs: 36, fat: 22, ingredients: ['Tortillas', 'Chicken breast', 'Romaine lettuce', 'Cheese (shredded)', 'Mayonnaise'], dietaryTags: ['nut-free', 'high-protein'], tips: 'Use leftover cooked chicken to make this in 5 minutes.' },
  { id: 'ln-chicken-rice-bowl', name: 'Chicken & Rice Bowl', mealType: 'lunch', categories: ['Lunch', 'Meal Prep', 'High Protein'], equipment: STOVE, cookMinutes: 25, cost: 2.80, calories: 520, protein: 38, carbs: 55, fat: 12, ingredients: ['Chicken breast', 'White rice', 'Broccoli', 'Soy sauce'], dietaryTags: ['dairy-free', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Classic meal-prep base — make 4 servings at once.' },
  { id: 'ln-veggie-pasta-salad', name: 'Pasta Salad', mealType: 'lunch', categories: ['Lunch', 'Meal Prep', 'Budget Friendly', 'Vegetarian'], equipment: STOVE, cookMinutes: 18, cost: 1.80, calories: 420, protein: 12, carbs: 60, fat: 14, ingredients: ['Pasta', 'Bell pepper', 'Tomato', 'Cheese (shredded)', 'Olive oil'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Eat cold — keeps 3 days in the fridge.' },
  { id: 'ln-hummus-wrap', name: 'Hummus Veggie Wrap', mealType: 'lunch', categories: ['Lunch', 'Vegetarian', 'Quick & Easy'], equipment: ANY, cookMinutes: 5, cost: 2.00, calories: 360, protein: 12, carbs: 48, fat: 14, ingredients: ['Tortillas', 'Canned chickpeas', 'Spinach', 'Bell pepper', 'Cucumber'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'low-cal'], tips: 'Mash chickpeas with olive oil and salt for quick hummus.' },
  { id: 'ln-chickpea-salad', name: 'Chickpea Salad', mealType: 'lunch', categories: ['Lunch', 'Vegetarian', 'High Protein', 'Budget Friendly'], equipment: ANY, cookMinutes: 8, cost: 1.70, calories: 340, protein: 15, carbs: 40, fat: 14, ingredients: ['Canned chickpeas', 'Cucumber', 'Tomato', 'Onion', 'Olive oil'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'low-cal'], tips: 'No cooking — just rinse, chop, and toss.' },
  { id: 'ln-blt', name: 'BLT Sandwich', mealType: 'lunch', categories: ['Lunch', 'Quick & Easy'], equipment: STOVE, cookMinutes: 10, cost: 2.60, calories: 460, protein: 18, carbs: 36, fat: 28, ingredients: ['Bread (loaf)', 'Deli turkey', 'Romaine lettuce', 'Tomato', 'Mayonnaise'], dietaryTags: ['nut-free'], tips: 'Toast the bread so it does not get soggy.' },
  { id: 'ln-loaded-baked-potato', name: 'Loaded Baked Potato', mealType: 'lunch', categories: ['Lunch', 'Budget Friendly', 'Vegetarian'], equipment: MICRO, cookMinutes: 12, cost: 1.50, calories: 420, protein: 14, carbs: 58, fat: 15, ingredients: ['Potato', 'Cheese (shredded)', 'Butter', 'Greek yogurt'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free'], tips: 'Microwave the potato 5–7 min, top with everything.' },
  { id: 'ln-egg-salad', name: 'Egg Salad Sandwich', mealType: 'lunch', categories: ['Lunch', 'High Protein', 'Budget Friendly'], equipment: STOVE, cookMinutes: 16, cost: 1.40, calories: 410, protein: 20, carbs: 30, fat: 24, ingredients: ['Eggs', 'Mayonnaise', 'Bread (loaf)', 'Salt'], dietaryTags: ['vegetarian', 'nut-free', 'high-protein'], tips: 'Mash hard-boiled eggs with mayo, salt, and pepper.' },
  { id: 'ln-tomato-soup-grilled-cheese', name: 'Tomato Soup & Grilled Cheese', mealType: 'lunch', categories: ['Lunch', 'Quick & Easy', 'Vegetarian'], equipment: STOVE, cookMinutes: 12, cost: 2.20, calories: 520, protein: 16, carbs: 50, fat: 28, ingredients: ['Bread (loaf)', 'Cheese (shredded)', 'Butter', 'Tomato'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Dip the grilled cheese — the ultimate comfort combo.' },
  { id: 'ln-rice-beans', name: 'Rice & Beans', mealType: 'lunch', categories: ['Lunch', 'Budget Friendly', 'Vegetarian', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 22, cost: 1.20, calories: 450, protein: 16, carbs: 78, fat: 8, ingredients: ['White rice', 'Canned black beans', 'Onion', 'Garlic', 'Hot sauce'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'high-protein'], tips: 'A complete protein for under a dollar fifty.' },
  { id: 'ln-cottage-toast', name: 'Cottage Cheese Toast', mealType: 'lunch', categories: ['Lunch', 'Quick & Easy', 'High Protein', 'Vegetarian'], equipment: STOVE, cookMinutes: 5, cost: 1.60, calories: 320, protein: 22, carbs: 30, fat: 12, ingredients: ['Bread (loaf)', 'Cottage cheese', 'Tomato', 'Black pepper'], dietaryTags: ['vegetarian', 'nut-free', 'high-protein', 'low-cal'], tips: 'Cottage cheese on toast with tomato and pepper.' },
  { id: 'ln-leftover-pizza', name: 'Frozen Pizza Slice', mealType: 'lunch', categories: ['Lunch', 'Quick & Easy', 'College Dorm'], equipment: STOVE, cookMinutes: 15, cost: 2.00, calories: 500, protein: 18, carbs: 56, fat: 22, ingredients: ['Frozen pizza'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Toaster oven gives a crispier crust than microwave.' },
  { id: 'ln-stir-fry-rice', name: 'Veggie Fried Rice', mealType: 'lunch', categories: ['Lunch', 'Budget Friendly', 'Vegetarian', 'Meal Prep'], equipment: STOVE, cookMinutes: 18, cost: 2.00, calories: 460, protein: 14, carbs: 62, fat: 16, ingredients: ['White rice', 'Eggs', 'Frozen vegetables', 'Soy sauce', 'Vegetable oil'], dietaryTags: ['vegetarian', 'dairy-free', 'nut-free'], tips: 'Day-old cold rice fries up best.' },
  { id: 'ln-greek-bowl', name: 'Greek Yogurt Chicken Bowl', mealType: 'lunch', categories: ['Lunch', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 20, cost: 3.20, calories: 480, protein: 42, carbs: 30, fat: 18, ingredients: ['Chicken breast', 'Greek yogurt', 'Cucumber', 'Tomato', 'White rice'], dietaryTags: ['gluten-free', 'nut-free', 'high-protein'], tips: 'Greek yogurt doubles as a high-protein sauce.' },
  { id: 'ln-soup-bread', name: 'Bean Soup & Bread', mealType: 'lunch', categories: ['Lunch', 'Budget Friendly', 'Vegetarian', 'Quick & Easy'], equipment: MICRO, cookMinutes: 8, cost: 1.40, calories: 380, protein: 16, carbs: 56, fat: 8, ingredients: ['Canned chickpeas', 'Tomato', 'Onion', 'Bread (loaf)'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'low-cal'], tips: 'Microwave beans and tomato, mash slightly, serve with bread.' },

  /* ════════════════ DINNER ════════════════ */
  { id: 'dn-garlic-pasta', name: 'Garlic Butter Pasta', mealType: 'dinner', categories: ['Dinner', 'Quick & Easy', 'Budget Friendly', 'College Dorm', 'Vegetarian'], equipment: STOVE, cookMinutes: 15, cost: 1.60, calories: 540, protein: 14, carbs: 78, fat: 18, ingredients: ['Pasta', 'Butter', 'Garlic', 'Cheese (shredded)', 'Black pepper'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Save a splash of pasta water to loosen the sauce.' },
  { id: 'dn-spaghetti', name: 'Spaghetti with Meat Sauce', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 25, cost: 2.80, calories: 620, protein: 32, carbs: 70, fat: 22, ingredients: ['Pasta', 'Ground beef', 'Tomato', 'Onion', 'Garlic'], dietaryTags: ['dairy-free', 'nut-free', 'high-protein'], tips: 'Brown the beef first, then simmer with crushed tomato.' },
  { id: 'dn-fried-rice', name: 'Egg Fried Rice', mealType: 'dinner', categories: ['Dinner', 'Budget Friendly', 'College Dorm', 'Vegetarian'], equipment: STOVE, cookMinutes: 20, cost: 2.00, calories: 560, protein: 16, carbs: 72, fat: 20, ingredients: ['White rice', 'Eggs', 'Frozen vegetables', 'Soy sauce', 'Vegetable oil'], dietaryTags: ['vegetarian', 'dairy-free', 'nut-free'], tips: 'High heat and cold rice are the secrets.' },
  { id: 'dn-chicken-stir-fry', name: 'Chicken Stir Fry', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 22, cost: 3.20, calories: 540, protein: 40, carbs: 50, fat: 18, ingredients: ['Chicken breast', 'Frozen vegetables', 'White rice', 'Soy sauce', 'Garlic'], dietaryTags: ['dairy-free', 'nut-free', 'high-protein'], tips: 'Cut chicken small so it cooks fast and evenly.' },
  { id: 'dn-beef-tacos', name: 'Beef Tacos', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Quick & Easy'], equipment: STOVE, cookMinutes: 18, cost: 2.90, calories: 560, protein: 30, carbs: 44, fat: 28, ingredients: ['Ground beef', 'Tortillas', 'Cheese (shredded)', 'Onion', 'Hot sauce'], dietaryTags: ['nut-free', 'high-protein'], tips: 'Season the beef with salt, pepper, and any chili powder.' },
  { id: 'dn-bean-tacos', name: 'Black Bean Tacos', mealType: 'dinner', categories: ['Dinner', 'Budget Friendly', 'Vegetarian', 'Quick & Easy'], equipment: STOVE, cookMinutes: 14, cost: 1.80, calories: 440, protein: 18, carbs: 58, fat: 16, ingredients: ['Canned black beans', 'Tortillas', 'Cheese (shredded)', 'Avocado', 'Hot sauce'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Mash half the beans for a refried-style filling.' },
  { id: 'dn-baked-chicken-veg', name: 'Baked Chicken & Veggies', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 35, cost: 3.40, calories: 480, protein: 44, carbs: 30, fat: 18, ingredients: ['Chicken breast', 'Broccoli', 'Potato', 'Olive oil', 'Garlic'], dietaryTags: ['dairy-free', 'gluten-free', 'nut-free', 'high-protein'], tips: 'One tray, 400°F, roast until chicken hits 165°F.' },
  { id: 'dn-pasta-marinara', name: 'Pasta Marinara', mealType: 'dinner', categories: ['Dinner', 'Budget Friendly', 'Vegetarian', 'Quick & Easy'], equipment: STOVE, cookMinutes: 20, cost: 1.70, calories: 520, protein: 16, carbs: 84, fat: 12, ingredients: ['Pasta', 'Tomato', 'Garlic', 'Onion', 'Olive oil'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'nut-free'], tips: 'Simmer tomato with garlic for 10 min for real sauce.' },
  { id: 'dn-tuna-pasta', name: 'Tuna Pasta', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Budget Friendly'], equipment: STOVE, cookMinutes: 18, cost: 2.20, calories: 540, protein: 32, carbs: 66, fat: 16, ingredients: ['Pasta', 'Canned tuna', 'Olive oil', 'Garlic', 'Black pepper'], dietaryTags: ['dairy-free', 'nut-free', 'high-protein'], tips: 'Toss drained tuna with hot pasta, oil, and garlic.' },
  { id: 'dn-stuffed-potato', name: 'Loaded Dinner Potato', mealType: 'dinner', categories: ['Dinner', 'Budget Friendly', 'Vegetarian', 'High Protein'], equipment: MICRO, cookMinutes: 14, cost: 2.00, calories: 500, protein: 20, carbs: 64, fat: 18, ingredients: ['Potato', 'Canned black beans', 'Cheese (shredded)', 'Greek yogurt', 'Hot sauce'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Microwave the potato, split, and pile on toppings.' },
  { id: 'dn-chicken-quesadilla', name: 'Chicken Quesadilla', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Quick & Easy'], equipment: STOVE, cookMinutes: 16, cost: 3.00, calories: 560, protein: 36, carbs: 40, fat: 26, ingredients: ['Tortillas', 'Chicken breast', 'Cheese (shredded)', 'Bell pepper', 'Onion'], dietaryTags: ['nut-free', 'high-protein'], tips: 'Pre-cook the chicken and peppers before assembling.' },
  { id: 'dn-ramen-stir', name: 'Ramen Stir Fry', mealType: 'dinner', categories: ['Dinner', 'College Dorm', 'Budget Friendly', 'Quick & Easy'], equipment: STOVE, cookMinutes: 14, cost: 1.60, calories: 520, protein: 16, carbs: 64, fat: 22, ingredients: ['Ramen noodles', 'Eggs', 'Frozen vegetables', 'Soy sauce', 'Vegetable oil'], dietaryTags: ['vegetarian', 'dairy-free', 'nut-free'], tips: 'Skip the seasoning packet; stir-fry the cooked noodles.' },
  { id: 'dn-chili', name: 'Quick Bean Chili', mealType: 'dinner', categories: ['Dinner', 'Budget Friendly', 'Vegetarian', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 25, cost: 1.90, calories: 420, protein: 20, carbs: 62, fat: 8, ingredients: ['Canned black beans', 'Canned chickpeas', 'Tomato', 'Onion', 'Garlic'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'high-protein'], tips: 'Add chili powder and cumin; simmer 15 min.' },
  { id: 'dn-beef-chili', name: 'Beef Chili', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 30, cost: 3.00, calories: 540, protein: 34, carbs: 48, fat: 22, ingredients: ['Ground beef', 'Canned black beans', 'Tomato', 'Onion', 'Garlic'], dietaryTags: ['dairy-free', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Makes a big batch — freezes beautifully.' },
  { id: 'dn-omelette-dinner', name: 'Dinner Veggie Omelette', mealType: 'dinner', categories: ['Dinner', 'Quick & Easy', 'High Protein', 'Vegetarian'], equipment: STOVE, cookMinutes: 12, cost: 2.20, calories: 400, protein: 24, carbs: 10, fat: 28, ingredients: ['Eggs', 'Cheese (shredded)', 'Spinach', 'Bell pepper', 'Onion'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Breakfast for dinner is fast, cheap, and protein-rich.' },
  { id: 'dn-tofu-stir-fry', name: 'Tofu Veggie Stir Fry', mealType: 'dinner', categories: ['Dinner', 'Vegetarian', 'High Protein'], equipment: STOVE, cookMinutes: 20, cost: 2.40, calories: 460, protein: 22, carbs: 52, fat: 18, ingredients: ['Tofu', 'White rice', 'Frozen vegetables', 'Soy sauce', 'Garlic'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'high-protein'], tips: 'Press tofu and pan-fry until golden before saucing.' },
  { id: 'dn-sheet-sausage', name: 'Sausage & Pepper Bowl', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 24, cost: 3.10, calories: 560, protein: 30, carbs: 44, fat: 28, ingredients: ['Ground beef', 'Bell pepper', 'Onion', 'White rice', 'Garlic'], dietaryTags: ['dairy-free', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Brown the meat with peppers and onions over rice.' },
  { id: 'dn-mac-broccoli', name: 'Mac & Cheese with Broccoli', mealType: 'dinner', categories: ['Dinner', 'College Dorm', 'Quick & Easy', 'Vegetarian'], equipment: MICRO, cookMinutes: 12, cost: 1.80, calories: 480, protein: 16, carbs: 64, fat: 18, ingredients: ['Mac & cheese (box)', 'Broccoli', 'Milk', 'Butter'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Steam broccoli in the microwave and stir it in.' },
  { id: 'dn-rice-bowl-egg', name: 'Soy Egg Rice Bowl', mealType: 'dinner', categories: ['Dinner', 'Budget Friendly', 'Quick & Easy', 'Vegetarian'], equipment: STOVE, cookMinutes: 15, cost: 1.40, calories: 480, protein: 16, carbs: 70, fat: 14, ingredients: ['White rice', 'Eggs', 'Soy sauce', 'Hot sauce'], dietaryTags: ['vegetarian', 'dairy-free', 'nut-free'], tips: 'Fry an egg, lay over hot rice, drizzle soy and chili.' },
  { id: 'dn-chicken-pasta', name: 'Creamy Chicken Pasta', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 25, cost: 3.30, calories: 640, protein: 42, carbs: 64, fat: 24, ingredients: ['Pasta', 'Chicken breast', 'Cream cheese', 'Garlic', 'Milk'], dietaryTags: ['nut-free', 'high-protein'], tips: 'Melt cream cheese with pasta water for an easy sauce.' },
  { id: 'dn-veggie-curry', name: 'Chickpea Curry & Rice', mealType: 'dinner', categories: ['Dinner', 'Vegetarian', 'Budget Friendly', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 25, cost: 2.20, calories: 520, protein: 18, carbs: 80, fat: 14, ingredients: ['Canned chickpeas', 'White rice', 'Tomato', 'Onion', 'Garlic'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'high-protein'], tips: 'Add curry powder and a splash of milk for richness.' },
  { id: 'dn-grilled-chicken-salad', name: 'Grilled Chicken Salad', mealType: 'dinner', categories: ['Dinner', 'High Protein'], equipment: STOVE, cookMinutes: 18, cost: 3.20, calories: 380, protein: 40, carbs: 16, fat: 18, ingredients: ['Chicken breast', 'Romaine lettuce', 'Tomato', 'Cucumber', 'Olive oil'], dietaryTags: ['dairy-free', 'gluten-free', 'nut-free', 'high-protein', 'low-cal'], tips: 'Slice warm chicken over crisp greens.' },
  { id: 'dn-pasta-primavera', name: 'Pasta Primavera', mealType: 'dinner', categories: ['Dinner', 'Vegetarian', 'Meal Prep'], equipment: STOVE, cookMinutes: 22, cost: 2.10, calories: 500, protein: 16, carbs: 74, fat: 16, ingredients: ['Pasta', 'Frozen vegetables', 'Garlic', 'Olive oil', 'Cheese (shredded)'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Toss pasta with sautéed veg, oil, garlic, and parmesan.' },
  { id: 'dn-burrito', name: 'Loaded Dinner Burrito', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Budget Friendly'], equipment: STOVE, cookMinutes: 18, cost: 2.60, calories: 600, protein: 26, carbs: 70, fat: 24, ingredients: ['Tortillas', 'White rice', 'Canned black beans', 'Cheese (shredded)', 'Hot sauce'], dietaryTags: ['vegetarian', 'nut-free', 'high-protein'], tips: 'Rice + beans + cheese, wrap tight, sear seam-side down.' },
  { id: 'dn-shrimp-rice', name: 'Garlic Shrimp Rice (Frozen)', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Quick & Easy'], equipment: STOVE, cookMinutes: 18, cost: 3.40, calories: 460, protein: 32, carbs: 56, fat: 10, ingredients: ['White rice', 'Frozen vegetables', 'Garlic', 'Soy sauce', 'Olive oil'], dietaryTags: ['dairy-free', 'nut-free', 'high-protein'], tips: 'Frozen shrimp cooks in 3–4 min — do not overcook.' },
  { id: 'dn-veg-soup', name: 'Hearty Vegetable Soup', mealType: 'dinner', categories: ['Dinner', 'Vegetarian', 'Budget Friendly', 'Meal Prep'], equipment: STOVE, cookMinutes: 28, cost: 1.60, calories: 320, protein: 12, carbs: 52, fat: 6, ingredients: ['Frozen vegetables', 'Canned chickpeas', 'Tomato', 'Onion', 'Garlic'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'low-cal'], tips: 'Simmer everything in broth or water for 20 min.' },
  { id: 'dn-pizza-toast', name: 'English Muffin Pizzas', mealType: 'dinner', categories: ['Dinner', 'College Dorm', 'Quick & Easy', 'Vegetarian'], equipment: STOVE, cookMinutes: 12, cost: 1.70, calories: 420, protein: 16, carbs: 48, fat: 18, ingredients: ['Bread (loaf)', 'Tomato', 'Cheese (shredded)', 'Garlic'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Toast bread, add sauce and cheese, broil until bubbly.' },
]

/* ════════════════════════════════════════════════════════════════
   DERIVED INDEXES & HELPERS
   ════════════════════════════════════════════════════════════════ */

/** Recipes grouped by meal type (for the generator pools). */
export const RECIPES_BY_MEAL: Record<MealTypeKey, LibraryRecipe[]> = {
  breakfast: RECIPE_LIBRARY.filter(r => r.mealType === 'breakfast'),
  lunch:     RECIPE_LIBRARY.filter(r => r.mealType === 'lunch'),
  dinner:    RECIPE_LIBRARY.filter(r => r.mealType === 'dinner'),
}

/** Count of recipes that list a given category (for badge display). */
export function recipeCountForCategory(category: string): number {
  if (category === 'All') return RECIPE_LIBRARY.length
  return RECIPE_LIBRARY.filter(r => r.categories.includes(category)).length
}

/**
 * Filter the library by category, free-text query, equipment, dietary tags,
 * and disliked ingredients. All filters are AND-combined.
 */
export function filterLibrary(opts: {
  category?:  string
  query?:     string
  equipment?: EquipmentTier[]
  dietary?:   string[]
  disliked?:  string[]
}): LibraryRecipe[] {
  const { category = 'All', query = '', equipment = [], dietary = [], disliked = [] } = opts
  const q     = query.trim().toLowerCase()
  const lower = disliked.map(d => d.toLowerCase())

  return RECIPE_LIBRARY.filter(r => {
    if (category !== 'All' && !r.categories.includes(category)) return false
    if (q) {
      const hay = `${r.name} ${r.ingredients.join(' ')} ${r.categories.join(' ')}`.toLowerCase()
      if (!hay.includes(q)) return false
    }
    if (equipment.length && !equipment.some(e => r.equipment.includes(e))) return false
    if (dietary.length  && !dietary.every(tag => r.dietaryTags.includes(tag))) return false
    if (lower.length) {
      const hasDisliked = r.ingredients.some(ing => lower.some(d => ing.toLowerCase().includes(d)))
      if (hasDisliked) return false
    }
    return true
  })
}
