/**
 * utils/recipeLibrary.ts — Built-in Recipe Library
 *
 * A large catalogue of basic, everyday recipes with full data:
 * ingredients, calories, macros (protein/carbs/fat), estimated cost
 * per serving, cook time, equipment tier, dietary tags, and a tip.
 *
 * Powers:
 *   • The browsable Recipe Library in the Recipes & Resources tab
 *   • The smart Week-Plan generator (calorie / protein / budget aware)
 *
 * Costs and calories are stored PER SERVING (already divided down),
 * so the generator can sum them directly without unit math.
 */

import type { EquipmentTier, MealTypeKey } from './mealData'

export interface LibraryRecipe {
  id:          string
  name:        string
  mealType:    MealTypeKey          // breakfast | lunch | dinner
  categories:  string[]             // subset of RECIPE_CATEGORIES (browse filter)
  equipment:   EquipmentTier[]      // tiers that can make it
  cookMinutes: number
  cost:        number               // USD per serving
  calories:    number               // kcal per serving
  protein:     number               // g per serving
  carbs:       number               // g per serving
  fat:         number               // g per serving
  ingredients: string[]
  dietaryTags: string[]
  tips:        string
}

/* Shorthands for equipment combos to keep the dataset compact */
const ANY:  EquipmentTier[] = ['no_kitchen', 'microwave', 'mini_fridge', 'hot_plate']
const MICRO: EquipmentTier[] = ['microwave', 'mini_fridge', 'hot_plate']
const FRIDGE: EquipmentTier[] = ['mini_fridge', 'hot_plate']
const STOVE: EquipmentTier[] = ['hot_plate']

export const RECIPE_LIBRARY: LibraryRecipe[] = [
  /* ════════════════ BREAKFAST ════════════════ */
  { id: 'bk-scrambled-eggs', name: 'Classic Scrambled Eggs', mealType: 'breakfast', categories: ['Breakfast', 'Quick & Easy', 'High Protein', 'Vegetarian'], equipment: STOVE, cookMinutes: 8, cost: 0.90, calories: 220, protein: 14, carbs: 2, fat: 16, ingredients: ['Eggs', 'Butter', 'Salt'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Low heat, stir constantly, pull off just before fully set.' },
  { id: 'bk-mug-eggs', name: 'Microwave Mug Eggs', mealType: 'breakfast', categories: ['Breakfast', 'College Dorm', 'Quick & Easy', 'High Protein', 'Vegetarian'], equipment: MICRO, cookMinutes: 3, cost: 1.00, calories: 230, protein: 16, carbs: 3, fat: 15, ingredients: ['Eggs', 'Milk', 'Cheese (shredded)', 'Salt'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free', 'high-protein'], tips: '30s, stir, 30s more so it does not overflow.' },
  { id: 'bk-overnight-oats', name: 'Overnight Oats', mealType: 'breakfast', categories: ['Breakfast', 'Meal Prep', 'Budget Friendly', 'Vegetarian'], equipment: FRIDGE, cookMinutes: 5, cost: 0.90, calories: 350, protein: 12, carbs: 55, fat: 9, ingredients: ['Oatmeal', 'Milk', 'Banana'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Mix in a jar at night, eat cold in the morning.' },
  { id: 'bk-pb-oats', name: 'Peanut Butter Oats', mealType: 'breakfast', categories: ['Breakfast', 'High Protein', 'Vegetarian'], equipment: MICRO, cookMinutes: 4, cost: 1.10, calories: 440, protein: 16, carbs: 56, fat: 18, ingredients: ['Oatmeal', 'Milk', 'Peanut butter', 'Banana'], dietaryTags: ['vegetarian'], tips: 'Stir peanut butter in while the oats are hot.' },
  { id: 'bk-yogurt-parfait', name: 'Yogurt Parfait', mealType: 'breakfast', categories: ['Breakfast', 'Quick & Easy', 'High Protein', 'Vegetarian'], equipment: ANY, cookMinutes: 3, cost: 1.80, calories: 280, protein: 18, carbs: 38, fat: 6, ingredients: ['Greek yogurt', 'Granola bar', 'Banana'], dietaryTags: ['vegetarian', 'gluten-free', 'high-protein'], tips: 'Layer yogurt, crushed granola, and fruit.' },
  { id: 'bk-avocado-toast', name: 'Avocado Toast', mealType: 'breakfast', categories: ['Breakfast', 'Quick & Easy', 'Vegetarian'], equipment: STOVE, cookMinutes: 7, cost: 1.70, calories: 320, protein: 8, carbs: 34, fat: 18, ingredients: ['Bread (loaf)', 'Avocado', 'Salt', 'Hot sauce'], dietaryTags: ['vegetarian', 'dairy-free', 'nut-free'], tips: 'Mash avocado with salt and a squeeze of lemon if you have it.' },
  { id: 'bk-avocado-egg-toast', name: 'Avocado & Egg Toast', mealType: 'breakfast', categories: ['Breakfast', 'High Protein', 'Vegetarian'], equipment: STOVE, cookMinutes: 9, cost: 2.20, calories: 430, protein: 17, carbs: 35, fat: 25, ingredients: ['Bread (loaf)', 'Avocado', 'Eggs', 'Salt'], dietaryTags: ['vegetarian', 'dairy-free', 'nut-free', 'high-protein'], tips: 'Fry or poach the egg and lay it over the mashed avocado.' },
  { id: 'bk-pb-banana-wrap', name: 'PB & Banana Wrap', mealType: 'breakfast', categories: ['Breakfast', 'College Dorm', 'Budget Friendly', 'Vegetarian'], equipment: ANY, cookMinutes: 3, cost: 1.10, calories: 420, protein: 12, carbs: 58, fat: 16, ingredients: ['Tortillas', 'Peanut butter', 'Banana'], dietaryTags: ['vegetarian', 'dairy-free', 'vegan'], tips: 'Spread, add banana, roll. No heat needed.' },
  { id: 'bk-cereal', name: 'Cereal & Milk', mealType: 'breakfast', categories: ['Breakfast', 'College Dorm', 'Quick & Easy', 'Budget Friendly', 'Vegetarian'], equipment: FRIDGE, cookMinutes: 2, cost: 0.70, calories: 270, protein: 8, carbs: 50, fat: 5, ingredients: ['Cereal', 'Milk'], dietaryTags: ['vegetarian'], tips: 'The dorm classic. Add banana for extra calories.' },
  { id: 'bk-banana-pancakes', name: '2-Ingredient Banana Pancakes', mealType: 'breakfast', categories: ['Breakfast', 'Quick & Easy', 'Vegetarian', 'High Protein'], equipment: STOVE, cookMinutes: 12, cost: 1.20, calories: 300, protein: 14, carbs: 30, fat: 13, ingredients: ['Banana', 'Eggs'], dietaryTags: ['vegetarian', 'gluten-free', 'dairy-free', 'nut-free', 'high-protein'], tips: 'Mash banana, whisk with eggs, cook small pancakes.' },
  { id: 'bk-french-toast', name: 'French Toast', mealType: 'breakfast', categories: ['Breakfast', 'Vegetarian'], equipment: STOVE, cookMinutes: 12, cost: 1.40, calories: 360, protein: 13, carbs: 42, fat: 14, ingredients: ['Bread (loaf)', 'Eggs', 'Milk', 'Butter'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Soak bread in egg-milk, fry in butter until golden.' },
  { id: 'bk-breakfast-burrito', name: 'Breakfast Burrito', mealType: 'breakfast', categories: ['Breakfast', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 12, cost: 1.80, calories: 480, protein: 24, carbs: 40, fat: 24, ingredients: ['Tortillas', 'Eggs', 'Cheese (shredded)', 'Canned black beans', 'Hot sauce'], dietaryTags: ['vegetarian', 'nut-free', 'high-protein'], tips: 'Wrap in foil; freezes well for grab-and-go.' },
  { id: 'bk-omelette', name: 'Cheese & Veggie Omelette', mealType: 'breakfast', categories: ['Breakfast', 'High Protein', 'Vegetarian'], equipment: STOVE, cookMinutes: 10, cost: 2.10, calories: 340, protein: 22, carbs: 6, fat: 25, ingredients: ['Eggs', 'Cheese (shredded)', 'Bell pepper', 'Onion', 'Butter'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Cook eggs gently, add fillings to one half, fold over.' },
  { id: 'bk-microwave-oatmeal', name: 'Microwave Oatmeal', mealType: 'breakfast', categories: ['Breakfast', 'College Dorm', 'Quick & Easy', 'Budget Friendly', 'Vegetarian'], equipment: MICRO, cookMinutes: 4, cost: 0.80, calories: 300, protein: 9, carbs: 50, fat: 6, ingredients: ['Oatmeal', 'Milk', 'Banana'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Watch it — oatmeal boils over fast in the microwave.' },
  { id: 'bk-cottage-cheese-bowl', name: 'Cottage Cheese & Fruit Bowl', mealType: 'breakfast', categories: ['Breakfast', 'Quick & Easy', 'High Protein', 'Vegetarian'], equipment: ANY, cookMinutes: 2, cost: 1.60, calories: 240, protein: 24, carbs: 18, fat: 6, ingredients: ['Cottage cheese', 'Banana', 'Granola bar'], dietaryTags: ['vegetarian', 'gluten-free', 'high-protein', 'low-cal'], tips: 'Top cottage cheese with fruit and a crushed granola bar.' },
  { id: 'bk-egg-cheese-sandwich', name: 'Egg & Cheese Sandwich', mealType: 'breakfast', categories: ['Breakfast', 'Quick & Easy', 'High Protein'], equipment: STOVE, cookMinutes: 8, cost: 1.60, calories: 410, protein: 21, carbs: 30, fat: 22, ingredients: ['Bread (loaf)', 'Eggs', 'Cheese (shredded)', 'Butter'], dietaryTags: ['vegetarian', 'nut-free', 'high-protein'], tips: 'Fry the egg hard so it stacks neatly.' },
  { id: 'bk-smoothie', name: 'Banana Berry Smoothie', mealType: 'breakfast', categories: ['Breakfast', 'Quick & Easy', 'Vegetarian', 'High Protein'], equipment: FRIDGE, cookMinutes: 4, cost: 1.90, calories: 300, protein: 18, carbs: 45, fat: 5, ingredients: ['Banana', 'Greek yogurt', 'Milk', 'Peanut butter'], dietaryTags: ['vegetarian', 'gluten-free'], tips: 'Frozen banana makes it thick and cold without ice.' },
  { id: 'bk-toast-jam', name: 'Toast with Butter & Jam', mealType: 'breakfast', categories: ['Breakfast', 'Budget Friendly', 'Quick & Easy', 'Vegetarian'], equipment: STOVE, cookMinutes: 4, cost: 0.50, calories: 250, protein: 5, carbs: 42, fat: 7, ingredients: ['Bread (loaf)', 'Butter', 'Jelly'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Fastest warm breakfast there is.' },
  { id: 'bk-bagel-cream-cheese', name: 'Bagel with Cream Cheese', mealType: 'breakfast', categories: ['Breakfast', 'Quick & Easy', 'Vegetarian'], equipment: ANY, cookMinutes: 4, cost: 1.30, calories: 380, protein: 11, carbs: 52, fat: 14, ingredients: ['Bread (loaf)', 'Cream cheese'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Toast first for the best texture.' },
  { id: 'bk-egg-muffins', name: 'Baked Egg Muffins', mealType: 'breakfast', categories: ['Breakfast', 'Meal Prep', 'High Protein', 'Vegetarian'], equipment: STOVE, cookMinutes: 22, cost: 1.50, calories: 200, protein: 16, carbs: 4, fat: 13, ingredients: ['Eggs', 'Cheese (shredded)', 'Spinach', 'Bell pepper'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free', 'high-protein', 'low-cal'], tips: 'Bake a batch in a toaster oven; reheat all week.' },
  { id: 'bk-protein-shake', name: 'Quick Protein Shake', mealType: 'breakfast', categories: ['Breakfast', 'Quick & Easy', 'High Protein'], equipment: ANY, cookMinutes: 2, cost: 1.40, calories: 260, protein: 28, carbs: 20, fat: 6, ingredients: ['Milk', 'Peanut butter', 'Banana'], dietaryTags: ['vegetarian', 'gluten-free', 'high-protein'], tips: 'Add a scoop of protein powder if you keep some.' },
  { id: 'bk-hard-boiled-eggs', name: 'Hard-Boiled Eggs & Toast', mealType: 'breakfast', categories: ['Breakfast', 'Meal Prep', 'High Protein', 'Budget Friendly'], equipment: STOVE, cookMinutes: 14, cost: 1.00, calories: 290, protein: 18, carbs: 26, fat: 12, ingredients: ['Eggs', 'Bread (loaf)', 'Salt'], dietaryTags: ['vegetarian', 'dairy-free', 'nut-free', 'high-protein'], tips: 'Boil a half-dozen at once and peel as you go.' },
  { id: 'bk-fruit-pb', name: 'Apple & Peanut Butter', mealType: 'breakfast', categories: ['Breakfast', 'Snacks', 'Quick & Easy', 'Budget Friendly', 'Vegetarian'], equipment: ANY, cookMinutes: 2, cost: 1.00, calories: 280, protein: 8, carbs: 32, fat: 16, ingredients: ['Apple', 'Peanut butter'], dietaryTags: ['vegetarian', 'gluten-free', 'dairy-free', 'vegan'], tips: 'Slice the apple and dip. Travels well to class.' },
  { id: 'bk-tofu-scramble', name: 'Tofu Scramble', mealType: 'breakfast', categories: ['Breakfast', 'Vegetarian', 'High Protein'], equipment: STOVE, cookMinutes: 12, cost: 1.80, calories: 250, protein: 20, carbs: 10, fat: 15, ingredients: ['Tofu', 'Spinach', 'Bell pepper', 'Soy sauce', 'Vegetable oil'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'high-protein', 'low-cal'], tips: 'Crumble firm tofu and cook like scrambled eggs.' },
  { id: 'bk-granola-yogurt-pb', name: 'High-Protein Yogurt Bowl', mealType: 'breakfast', categories: ['Breakfast', 'High Protein', 'Vegetarian', 'Meal Prep'], equipment: ANY, cookMinutes: 3, cost: 2.00, calories: 360, protein: 28, carbs: 34, fat: 12, ingredients: ['Greek yogurt', 'Peanut butter', 'Banana', 'Oatmeal'], dietaryTags: ['vegetarian', 'high-protein'], tips: 'Greek yogurt plus PB pushes the protein over 25g.' },

  /* ════════════════ LUNCH ════════════════ */
  { id: 'ln-turkey-sandwich', name: 'Turkey & Cheese Sandwich', mealType: 'lunch', categories: ['Lunch', 'Quick & Easy', 'College Dorm', 'High Protein'], equipment: ANY, cookMinutes: 4, cost: 2.40, calories: 430, protein: 26, carbs: 38, fat: 18, ingredients: ['Bread (loaf)', 'Deli turkey', 'Cheese (shredded)', 'Mayonnaise'], dietaryTags: ['nut-free', 'high-protein'], tips: 'Add lettuce and tomato if you have them.' },
  { id: 'ln-pbj', name: 'Peanut Butter & Jelly', mealType: 'lunch', categories: ['Lunch', 'Budget Friendly', 'Quick & Easy', 'College Dorm', 'Vegetarian'], equipment: ANY, cookMinutes: 3, cost: 0.60, calories: 380, protein: 12, carbs: 50, fat: 16, ingredients: ['Bread (loaf)', 'Peanut butter', 'Jelly'], dietaryTags: ['vegetarian', 'dairy-free'], tips: 'The cheapest reliable lunch on campus.' },
  { id: 'ln-tuna-sandwich', name: 'Tuna Salad Sandwich', mealType: 'lunch', categories: ['Lunch', 'High Protein', 'Budget Friendly', 'Quick & Easy'], equipment: ANY, cookMinutes: 6, cost: 2.00, calories: 400, protein: 28, carbs: 34, fat: 16, ingredients: ['Canned tuna', 'Mayonnaise', 'Bread (loaf)'], dietaryTags: ['nut-free', 'high-protein'], tips: 'Mix tuna with mayo and pepper; spread thick.' },
  { id: 'ln-upgraded-ramen', name: 'Upgraded Ramen Bowl', mealType: 'lunch', categories: ['Lunch', 'College Dorm', 'Budget Friendly', 'High Protein'], equipment: MICRO, cookMinutes: 6, cost: 1.50, calories: 450, protein: 18, carbs: 55, fat: 16, ingredients: ['Ramen noodles', 'Eggs', 'Spinach', 'Soy sauce'], dietaryTags: ['dairy-free', 'nut-free'], tips: 'Crack an egg in halfway through cooking.' },
  { id: 'ln-quesadilla', name: 'Cheese Quesadilla', mealType: 'lunch', categories: ['Lunch', 'Quick & Easy', 'College Dorm', 'Vegetarian'], equipment: STOVE, cookMinutes: 8, cost: 1.80, calories: 420, protein: 16, carbs: 38, fat: 22, ingredients: ['Tortillas', 'Cheese (shredded)', 'Butter'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Crisp both sides in a buttered pan, slice into wedges.' },
  { id: 'ln-bean-quesadilla', name: 'Bean & Cheese Quesadilla', mealType: 'lunch', categories: ['Lunch', 'Budget Friendly', 'Vegetarian', 'High Protein'], equipment: STOVE, cookMinutes: 9, cost: 1.90, calories: 470, protein: 20, carbs: 50, fat: 20, ingredients: ['Tortillas', 'Canned black beans', 'Cheese (shredded)', 'Hot sauce'], dietaryTags: ['vegetarian', 'nut-free', 'high-protein'], tips: 'Mash the beans so the quesadilla holds together.' },
  { id: 'ln-microwave-mac', name: 'Microwave Mac & Cheese', mealType: 'lunch', categories: ['Lunch', 'College Dorm', 'Quick & Easy', 'Budget Friendly', 'Vegetarian'], equipment: MICRO, cookMinutes: 8, cost: 1.50, calories: 430, protein: 12, carbs: 60, fat: 15, ingredients: ['Mac & cheese (box)', 'Milk', 'Butter'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'A splash of milk makes the sauce creamier.' },
  { id: 'ln-burrito-bowl', name: 'Burrito Bowl', mealType: 'lunch', categories: ['Lunch', 'College Dorm', 'High Protein'], equipment: MICRO, cookMinutes: 8, cost: 2.50, calories: 490, protein: 22, carbs: 60, fat: 16, ingredients: ['White rice', 'Canned black beans', 'Cheese (shredded)', 'Hot sauce'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Rice, beans, cheese, salsa — layer in a bowl.' },
  { id: 'ln-grilled-cheese', name: 'Grilled Cheese', mealType: 'lunch', categories: ['Lunch', 'Quick & Easy', 'Budget Friendly', 'College Dorm', 'Vegetarian'], equipment: STOVE, cookMinutes: 7, cost: 1.20, calories: 400, protein: 14, carbs: 34, fat: 24, ingredients: ['Bread (loaf)', 'Cheese (shredded)', 'Butter'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Low-medium heat so the cheese melts before the bread burns.' },
  { id: 'ln-chicken-wrap', name: 'Chicken Caesar Wrap', mealType: 'lunch', categories: ['Lunch', 'High Protein', 'Quick & Easy'], equipment: STOVE, cookMinutes: 12, cost: 2.30, calories: 480, protein: 34, carbs: 36, fat: 22, ingredients: ['Tortillas', 'Chicken breast', 'Romaine lettuce', 'Cheese (shredded)', 'Mayonnaise'], dietaryTags: ['nut-free', 'high-protein'], tips: 'Use leftover cooked chicken to make this in 5 minutes.' },
  { id: 'ln-chicken-rice-bowl', name: 'Chicken & Rice Bowl', mealType: 'lunch', categories: ['Lunch', 'Meal Prep', 'High Protein'], equipment: STOVE, cookMinutes: 25, cost: 2.10, calories: 520, protein: 38, carbs: 55, fat: 12, ingredients: ['Chicken breast', 'White rice', 'Broccoli', 'Soy sauce'], dietaryTags: ['dairy-free', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Classic meal-prep base — make 4 servings at once.' },
  { id: 'ln-veggie-pasta-salad', name: 'Pasta Salad', mealType: 'lunch', categories: ['Lunch', 'Meal Prep', 'Budget Friendly', 'Vegetarian'], equipment: STOVE, cookMinutes: 18, cost: 1.80, calories: 420, protein: 12, carbs: 60, fat: 14, ingredients: ['Pasta', 'Bell pepper', 'Tomato', 'Cheese (shredded)', 'Olive oil'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Eat cold — keeps 3 days in the fridge.' },
  { id: 'ln-hummus-wrap', name: 'Hummus Veggie Wrap', mealType: 'lunch', categories: ['Lunch', 'Vegetarian', 'Quick & Easy'], equipment: ANY, cookMinutes: 5, cost: 2.00, calories: 360, protein: 12, carbs: 48, fat: 14, ingredients: ['Tortillas', 'Canned chickpeas', 'Spinach', 'Bell pepper', 'Cucumber'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'low-cal'], tips: 'Mash chickpeas with olive oil and salt for quick hummus.' },
  { id: 'ln-chickpea-salad', name: 'Chickpea Salad', mealType: 'lunch', categories: ['Lunch', 'Vegetarian', 'High Protein', 'Budget Friendly'], equipment: ANY, cookMinutes: 8, cost: 1.70, calories: 340, protein: 15, carbs: 40, fat: 14, ingredients: ['Canned chickpeas', 'Cucumber', 'Tomato', 'Onion', 'Olive oil'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'low-cal'], tips: 'No cooking — just rinse, chop, and toss.' },
  { id: 'ln-blt', name: 'BLT Sandwich', mealType: 'lunch', categories: ['Lunch', 'Quick & Easy'], equipment: STOVE, cookMinutes: 10, cost: 2.00, calories: 460, protein: 18, carbs: 36, fat: 28, ingredients: ['Bread (loaf)', 'Deli turkey', 'Romaine lettuce', 'Tomato', 'Mayonnaise'], dietaryTags: ['nut-free'], tips: 'Toast the bread so it does not get soggy.' },
  { id: 'ln-loaded-baked-potato', name: 'Loaded Baked Potato', mealType: 'lunch', categories: ['Lunch', 'Budget Friendly', 'Vegetarian'], equipment: MICRO, cookMinutes: 12, cost: 1.50, calories: 420, protein: 14, carbs: 58, fat: 15, ingredients: ['Potato', 'Cheese (shredded)', 'Butter', 'Greek yogurt'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free'], tips: 'Microwave the potato 5–7 min, top with everything.' },
  { id: 'ln-egg-salad', name: 'Egg Salad Sandwich', mealType: 'lunch', categories: ['Lunch', 'High Protein', 'Budget Friendly'], equipment: STOVE, cookMinutes: 16, cost: 1.40, calories: 410, protein: 20, carbs: 30, fat: 24, ingredients: ['Eggs', 'Mayonnaise', 'Bread (loaf)', 'Salt'], dietaryTags: ['vegetarian', 'nut-free', 'high-protein'], tips: 'Mash hard-boiled eggs with mayo, salt, and pepper.' },
  { id: 'ln-tomato-soup-grilled-cheese', name: 'Tomato Soup & Grilled Cheese', mealType: 'lunch', categories: ['Lunch', 'Quick & Easy', 'Vegetarian'], equipment: STOVE, cookMinutes: 12, cost: 2.20, calories: 520, protein: 16, carbs: 50, fat: 28, ingredients: ['Bread (loaf)', 'Cheese (shredded)', 'Butter', 'Tomato'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Dip the grilled cheese — the ultimate comfort combo.' },
  { id: 'ln-rice-beans', name: 'Rice & Beans', mealType: 'lunch', categories: ['Lunch', 'Budget Friendly', 'Vegetarian', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 22, cost: 1.20, calories: 450, protein: 16, carbs: 78, fat: 8, ingredients: ['White rice', 'Canned black beans', 'Onion', 'Garlic', 'Hot sauce'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'high-protein'], tips: 'A complete protein for under a dollar fifty.' },
  { id: 'ln-cottage-toast', name: 'Cottage Cheese Toast', mealType: 'lunch', categories: ['Lunch', 'Quick & Easy', 'High Protein', 'Vegetarian'], equipment: STOVE, cookMinutes: 5, cost: 1.60, calories: 320, protein: 22, carbs: 30, fat: 12, ingredients: ['Bread (loaf)', 'Cottage cheese', 'Tomato', 'Black pepper'], dietaryTags: ['vegetarian', 'nut-free', 'high-protein', 'low-cal'], tips: 'Cottage cheese on toast with tomato and pepper.' },
  { id: 'ln-leftover-pizza', name: 'Frozen Pizza Slice', mealType: 'lunch', categories: ['Lunch', 'Quick & Easy', 'College Dorm'], equipment: STOVE, cookMinutes: 15, cost: 2.00, calories: 500, protein: 18, carbs: 56, fat: 22, ingredients: ['Frozen pizza'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Toaster oven gives a crispier crust than microwave.' },
  { id: 'ln-stir-fry-rice', name: 'Veggie Fried Rice', mealType: 'lunch', categories: ['Lunch', 'Budget Friendly', 'Vegetarian', 'Meal Prep'], equipment: STOVE, cookMinutes: 18, cost: 2.00, calories: 460, protein: 14, carbs: 62, fat: 16, ingredients: ['White rice', 'Eggs', 'Frozen vegetables', 'Soy sauce', 'Vegetable oil'], dietaryTags: ['vegetarian', 'dairy-free', 'nut-free'], tips: 'Day-old cold rice fries up best.' },
  { id: 'ln-greek-bowl', name: 'Greek Yogurt Chicken Bowl', mealType: 'lunch', categories: ['Lunch', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 20, cost: 2.40, calories: 480, protein: 42, carbs: 30, fat: 18, ingredients: ['Chicken breast', 'Greek yogurt', 'Cucumber', 'Tomato', 'White rice'], dietaryTags: ['gluten-free', 'nut-free', 'high-protein'], tips: 'Greek yogurt doubles as a high-protein sauce.' },
  { id: 'ln-soup-bread', name: 'Bean Soup & Bread', mealType: 'lunch', categories: ['Lunch', 'Budget Friendly', 'Vegetarian', 'Quick & Easy'], equipment: MICRO, cookMinutes: 8, cost: 1.40, calories: 380, protein: 16, carbs: 56, fat: 8, ingredients: ['Canned chickpeas', 'Tomato', 'Onion', 'Bread (loaf)'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'low-cal'], tips: 'Microwave beans and tomato, mash slightly, serve with bread.' },

  /* ════════════════ DINNER ════════════════ */
  { id: 'dn-garlic-pasta', name: 'Garlic Butter Pasta', mealType: 'dinner', categories: ['Dinner', 'Quick & Easy', 'Budget Friendly', 'College Dorm', 'Vegetarian'], equipment: STOVE, cookMinutes: 15, cost: 1.60, calories: 540, protein: 14, carbs: 78, fat: 18, ingredients: ['Pasta', 'Butter', 'Garlic', 'Cheese (shredded)', 'Black pepper'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Save a splash of pasta water to loosen the sauce.' },
  { id: 'dn-spaghetti', name: 'Spaghetti with Meat Sauce', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 25, cost: 2.80, calories: 620, protein: 32, carbs: 70, fat: 22, ingredients: ['Pasta', 'Ground beef', 'Tomato', 'Onion', 'Garlic'], dietaryTags: ['dairy-free', 'nut-free', 'high-protein'], tips: 'Brown the beef first, then simmer with crushed tomato.' },
  { id: 'dn-fried-rice', name: 'Egg Fried Rice', mealType: 'dinner', categories: ['Dinner', 'Budget Friendly', 'College Dorm', 'Vegetarian'], equipment: STOVE, cookMinutes: 20, cost: 2.00, calories: 560, protein: 16, carbs: 72, fat: 20, ingredients: ['White rice', 'Eggs', 'Frozen vegetables', 'Soy sauce', 'Vegetable oil'], dietaryTags: ['vegetarian', 'dairy-free', 'nut-free'], tips: 'High heat and cold rice are the secrets.' },
  { id: 'dn-chicken-stir-fry', name: 'Chicken Stir Fry', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 22, cost: 2.40, calories: 540, protein: 40, carbs: 50, fat: 18, ingredients: ['Chicken breast', 'Frozen vegetables', 'White rice', 'Soy sauce', 'Garlic'], dietaryTags: ['dairy-free', 'nut-free', 'high-protein'], tips: 'Cut chicken small so it cooks fast and evenly.' },
  { id: 'dn-beef-tacos', name: 'Beef Tacos', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Quick & Easy'], equipment: STOVE, cookMinutes: 18, cost: 2.20, calories: 560, protein: 30, carbs: 44, fat: 28, ingredients: ['Ground beef', 'Tortillas', 'Cheese (shredded)', 'Onion', 'Hot sauce'], dietaryTags: ['nut-free', 'high-protein'], tips: 'Season the beef with salt, pepper, and any chili powder.' },
  { id: 'dn-bean-tacos', name: 'Black Bean Tacos', mealType: 'dinner', categories: ['Dinner', 'Budget Friendly', 'Vegetarian', 'Quick & Easy'], equipment: STOVE, cookMinutes: 14, cost: 1.80, calories: 440, protein: 18, carbs: 58, fat: 16, ingredients: ['Canned black beans', 'Tortillas', 'Cheese (shredded)', 'Avocado', 'Hot sauce'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Mash half the beans for a refried-style filling.' },
  { id: 'dn-baked-chicken-veg', name: 'Baked Chicken & Veggies', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 35, cost: 2.60, calories: 480, protein: 44, carbs: 30, fat: 18, ingredients: ['Chicken breast', 'Broccoli', 'Potato', 'Olive oil', 'Garlic'], dietaryTags: ['dairy-free', 'gluten-free', 'nut-free', 'high-protein'], tips: 'One tray, 400°F, roast until chicken hits 165°F.' },
  { id: 'dn-pasta-marinara', name: 'Pasta Marinara', mealType: 'dinner', categories: ['Dinner', 'Budget Friendly', 'Vegetarian', 'Quick & Easy'], equipment: STOVE, cookMinutes: 20, cost: 1.70, calories: 520, protein: 16, carbs: 84, fat: 12, ingredients: ['Pasta', 'Tomato', 'Garlic', 'Onion', 'Olive oil'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'nut-free'], tips: 'Simmer tomato with garlic for 10 min for real sauce.' },
  { id: 'dn-tuna-pasta', name: 'Tuna Pasta', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Budget Friendly'], equipment: STOVE, cookMinutes: 18, cost: 2.20, calories: 540, protein: 32, carbs: 66, fat: 16, ingredients: ['Pasta', 'Canned tuna', 'Olive oil', 'Garlic', 'Black pepper'], dietaryTags: ['dairy-free', 'nut-free', 'high-protein'], tips: 'Toss drained tuna with hot pasta, oil, and garlic.' },
  { id: 'dn-stuffed-potato', name: 'Loaded Dinner Potato', mealType: 'dinner', categories: ['Dinner', 'Budget Friendly', 'Vegetarian', 'High Protein'], equipment: MICRO, cookMinutes: 14, cost: 2.00, calories: 500, protein: 20, carbs: 64, fat: 18, ingredients: ['Potato', 'Canned black beans', 'Cheese (shredded)', 'Greek yogurt', 'Hot sauce'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Microwave the potato, split, and pile on toppings.' },
  { id: 'dn-chicken-quesadilla', name: 'Chicken Quesadilla', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Quick & Easy'], equipment: STOVE, cookMinutes: 16, cost: 2.20, calories: 560, protein: 36, carbs: 40, fat: 26, ingredients: ['Tortillas', 'Chicken breast', 'Cheese (shredded)', 'Bell pepper', 'Onion'], dietaryTags: ['nut-free', 'high-protein'], tips: 'Pre-cook the chicken and peppers before assembling.' },
  { id: 'dn-ramen-stir', name: 'Ramen Stir Fry', mealType: 'dinner', categories: ['Dinner', 'College Dorm', 'Budget Friendly', 'Quick & Easy'], equipment: STOVE, cookMinutes: 14, cost: 1.60, calories: 520, protein: 16, carbs: 64, fat: 22, ingredients: ['Ramen noodles', 'Eggs', 'Frozen vegetables', 'Soy sauce', 'Vegetable oil'], dietaryTags: ['vegetarian', 'dairy-free', 'nut-free'], tips: 'Skip the seasoning packet; stir-fry the cooked noodles.' },
  { id: 'dn-chili', name: 'Quick Bean Chili', mealType: 'dinner', categories: ['Dinner', 'Budget Friendly', 'Vegetarian', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 25, cost: 1.90, calories: 420, protein: 20, carbs: 62, fat: 8, ingredients: ['Canned black beans', 'Canned chickpeas', 'Tomato', 'Onion', 'Garlic'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'high-protein'], tips: 'Add chili powder and cumin; simmer 15 min.' },
  { id: 'dn-beef-chili', name: 'Beef Chili', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 30, cost: 2.20, calories: 540, protein: 34, carbs: 48, fat: 22, ingredients: ['Ground beef', 'Canned black beans', 'Tomato', 'Onion', 'Garlic'], dietaryTags: ['dairy-free', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Makes a big batch — freezes beautifully.' },
  { id: 'dn-omelette-dinner', name: 'Dinner Veggie Omelette', mealType: 'dinner', categories: ['Dinner', 'Quick & Easy', 'High Protein', 'Vegetarian'], equipment: STOVE, cookMinutes: 12, cost: 2.20, calories: 400, protein: 24, carbs: 10, fat: 28, ingredients: ['Eggs', 'Cheese (shredded)', 'Spinach', 'Bell pepper', 'Onion'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Breakfast for dinner is fast, cheap, and protein-rich.' },
  { id: 'dn-tofu-stir-fry', name: 'Tofu Veggie Stir Fry', mealType: 'dinner', categories: ['Dinner', 'Vegetarian', 'High Protein'], equipment: STOVE, cookMinutes: 20, cost: 2.40, calories: 460, protein: 22, carbs: 52, fat: 18, ingredients: ['Tofu', 'White rice', 'Frozen vegetables', 'Soy sauce', 'Garlic'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'high-protein'], tips: 'Press tofu and pan-fry until golden before saucing.' },
  { id: 'dn-sheet-sausage', name: 'Sausage & Pepper Bowl', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 24, cost: 2.30, calories: 560, protein: 30, carbs: 44, fat: 28, ingredients: ['Ground beef', 'Bell pepper', 'Onion', 'White rice', 'Garlic'], dietaryTags: ['dairy-free', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Brown the meat with peppers and onions over rice.' },
  { id: 'dn-mac-broccoli', name: 'Mac & Cheese with Broccoli', mealType: 'dinner', categories: ['Dinner', 'College Dorm', 'Quick & Easy', 'Vegetarian'], equipment: MICRO, cookMinutes: 12, cost: 1.80, calories: 480, protein: 16, carbs: 64, fat: 18, ingredients: ['Mac & cheese (box)', 'Broccoli', 'Milk', 'Butter'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Steam broccoli in the microwave and stir it in.' },
  { id: 'dn-rice-bowl-egg', name: 'Soy Egg Rice Bowl', mealType: 'dinner', categories: ['Dinner', 'Budget Friendly', 'Quick & Easy', 'Vegetarian'], equipment: STOVE, cookMinutes: 15, cost: 1.40, calories: 480, protein: 16, carbs: 70, fat: 14, ingredients: ['White rice', 'Eggs', 'Soy sauce', 'Hot sauce'], dietaryTags: ['vegetarian', 'dairy-free', 'nut-free'], tips: 'Fry an egg, lay over hot rice, drizzle soy and chili.' },
  { id: 'dn-chicken-pasta', name: 'Creamy Chicken Pasta', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 25, cost: 2.60, calories: 640, protein: 42, carbs: 64, fat: 24, ingredients: ['Pasta', 'Chicken breast', 'Cream cheese', 'Garlic', 'Milk'], dietaryTags: ['nut-free', 'high-protein'], tips: 'Melt cream cheese with pasta water for an easy sauce.' },
  { id: 'dn-veggie-curry', name: 'Chickpea Curry & Rice', mealType: 'dinner', categories: ['Dinner', 'Vegetarian', 'Budget Friendly', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 25, cost: 2.20, calories: 520, protein: 18, carbs: 80, fat: 14, ingredients: ['Canned chickpeas', 'White rice', 'Tomato', 'Onion', 'Garlic'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'high-protein'], tips: 'Add curry powder and a splash of milk for richness.' },
  { id: 'dn-grilled-chicken-salad', name: 'Grilled Chicken Salad', mealType: 'dinner', categories: ['Dinner', 'High Protein'], equipment: STOVE, cookMinutes: 18, cost: 2.40, calories: 380, protein: 40, carbs: 16, fat: 18, ingredients: ['Chicken breast', 'Romaine lettuce', 'Tomato', 'Cucumber', 'Olive oil'], dietaryTags: ['dairy-free', 'gluten-free', 'nut-free', 'high-protein', 'low-cal'], tips: 'Slice warm chicken over crisp greens.' },
  { id: 'dn-pasta-primavera', name: 'Pasta Primavera', mealType: 'dinner', categories: ['Dinner', 'Vegetarian', 'Meal Prep'], equipment: STOVE, cookMinutes: 22, cost: 2.10, calories: 500, protein: 16, carbs: 74, fat: 16, ingredients: ['Pasta', 'Frozen vegetables', 'Garlic', 'Olive oil', 'Cheese (shredded)'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Toss pasta with sautéed veg, oil, garlic, and parmesan.' },
  { id: 'dn-burrito', name: 'Loaded Dinner Burrito', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Budget Friendly'], equipment: STOVE, cookMinutes: 18, cost: 2.60, calories: 600, protein: 26, carbs: 70, fat: 24, ingredients: ['Tortillas', 'White rice', 'Canned black beans', 'Cheese (shredded)', 'Hot sauce'], dietaryTags: ['vegetarian', 'nut-free', 'high-protein'], tips: 'Rice + beans + cheese, wrap tight, sear seam-side down.' },
  { id: 'dn-shrimp-rice', name: 'Garlic Shrimp Rice (Frozen)', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Quick & Easy'], equipment: STOVE, cookMinutes: 18, cost: 2.00, calories: 460, protein: 32, carbs: 56, fat: 10, ingredients: ['White rice', 'Frozen vegetables', 'Garlic', 'Soy sauce', 'Olive oil'], dietaryTags: ['dairy-free', 'nut-free', 'high-protein'], tips: 'Frozen shrimp cooks in 3–4 min — do not overcook.' },
  { id: 'dn-veg-soup', name: 'Hearty Vegetable Soup', mealType: 'dinner', categories: ['Dinner', 'Vegetarian', 'Budget Friendly', 'Meal Prep'], equipment: STOVE, cookMinutes: 28, cost: 1.60, calories: 320, protein: 12, carbs: 52, fat: 6, ingredients: ['Frozen vegetables', 'Canned chickpeas', 'Tomato', 'Onion', 'Garlic'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'low-cal'], tips: 'Simmer everything in broth or water for 20 min.' },
  { id: 'dn-pizza-toast', name: 'English Muffin Pizzas', mealType: 'dinner', categories: ['Dinner', 'College Dorm', 'Quick & Easy', 'Vegetarian'], equipment: STOVE, cookMinutes: 12, cost: 1.70, calories: 420, protein: 16, carbs: 48, fat: 18, ingredients: ['Bread (loaf)', 'Tomato', 'Cheese (shredded)', 'Garlic'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Toast bread, add sauce and cheese, broil until bubbly.' },

  /* ════════════════ BREAKFAST (continued) ════════════════ */
  { id: 'bk-chia-pudding', name: 'Chia Seed Pudding', mealType: 'breakfast', categories: ['Breakfast', 'Meal Prep', 'Vegetarian', 'High Protein'], equipment: FRIDGE, cookMinutes: 5, cost: 1.40, calories: 280, protein: 10, carbs: 34, fat: 14, ingredients: ['Chia seeds', 'Milk', 'Banana', 'Peanut butter'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free'], tips: 'Stir chia into milk, refrigerate overnight, top with fruit.' },
  { id: 'bk-protein-pancakes', name: 'High-Protein Pancakes', mealType: 'breakfast', categories: ['Breakfast', 'High Protein', 'Vegetarian'], equipment: STOVE, cookMinutes: 14, cost: 1.60, calories: 380, protein: 28, carbs: 36, fat: 12, ingredients: ['Eggs', 'Cottage cheese', 'Oatmeal', 'Banana'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Blend all ingredients, cook on medium-low. Fluffy and filling.' },
  { id: 'bk-egg-white-scramble', name: 'Egg White Scramble', mealType: 'breakfast', categories: ['Breakfast', 'High Protein', 'Vegetarian', 'Quick & Easy'], equipment: STOVE, cookMinutes: 7, cost: 1.10, calories: 160, protein: 22, carbs: 4, fat: 5, ingredients: ['Eggs', 'Spinach', 'Bell pepper', 'Salt'], dietaryTags: ['vegetarian', 'gluten-free', 'dairy-free', 'nut-free', 'high-protein', 'low-cal'], tips: 'Use only whites or an egg white carton for max protein, minimal fat.' },
  { id: 'bk-smoked-salmon-toast', name: 'Smoked Salmon Toast', mealType: 'breakfast', categories: ['Breakfast', 'High Protein', 'Quick & Easy'], equipment: ANY, cookMinutes: 5, cost: 2.20, calories: 340, protein: 22, carbs: 28, fat: 14, ingredients: ['Bread (loaf)', 'Cream cheese', 'Cucumber', 'Dill'], dietaryTags: ['nut-free', 'high-protein'], tips: 'Spread cream cheese thick, layer salmon, top with cucumber.' },
  { id: 'bk-greek-yogurt-honey', name: 'Greek Yogurt with Honey & Nuts', mealType: 'breakfast', categories: ['Breakfast', 'Quick & Easy', 'High Protein', 'Vegetarian'], equipment: ANY, cookMinutes: 2, cost: 1.70, calories: 290, protein: 20, carbs: 30, fat: 10, ingredients: ['Greek yogurt', 'Peanut butter', 'Banana'], dietaryTags: ['vegetarian', 'gluten-free', 'high-protein'], tips: 'Drizzle honey and add any nuts you have for crunch.' },
  { id: 'bk-microwave-breakfast-sandwich', name: 'Microwave Breakfast Sandwich', mealType: 'breakfast', categories: ['Breakfast', 'College Dorm', 'Quick & Easy', 'High Protein'], equipment: MICRO, cookMinutes: 4, cost: 1.80, calories: 390, protein: 22, carbs: 32, fat: 18, ingredients: ['Bread (loaf)', 'Eggs', 'Cheese (shredded)', 'Deli turkey'], dietaryTags: ['nut-free', 'high-protein'], tips: 'Microwave egg in a mug, slide onto toast with cheese.' },
  { id: 'bk-coconut-oatmeal', name: 'Coconut Milk Oatmeal', mealType: 'breakfast', categories: ['Breakfast', 'Vegetarian', 'Budget Friendly', 'Meal Prep'], equipment: MICRO, cookMinutes: 5, cost: 1.20, calories: 380, protein: 8, carbs: 58, fat: 14, ingredients: ['Oatmeal', 'Milk', 'Banana', 'Peanut butter'], dietaryTags: ['vegetarian', 'dairy-free', 'vegan', 'gluten-free'], tips: 'Use canned coconut milk diluted 1:1 with water for richness.' },
  { id: 'bk-breakfast-hash', name: 'Potato Veggie Breakfast Hash', mealType: 'breakfast', categories: ['Breakfast', 'Vegetarian', 'Budget Friendly'], equipment: STOVE, cookMinutes: 18, cost: 1.50, calories: 380, protein: 10, carbs: 50, fat: 16, ingredients: ['Potato', 'Eggs', 'Bell pepper', 'Onion', 'Vegetable oil'], dietaryTags: ['vegetarian', 'gluten-free', 'dairy-free', 'nut-free'], tips: 'Dice potatoes small so they cook through in 12–15 min.' },
  { id: 'bk-cottage-pancakes', name: 'Cottage Cheese Pancakes', mealType: 'breakfast', categories: ['Breakfast', 'High Protein', 'Vegetarian'], equipment: STOVE, cookMinutes: 14, cost: 1.50, calories: 320, protein: 24, carbs: 28, fat: 12, ingredients: ['Cottage cheese', 'Eggs', 'Oatmeal'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Blend until smooth for fluffy texture; very high protein for pancakes.' },
  { id: 'bk-almond-butter-toast', name: 'Almond Butter & Banana Toast', mealType: 'breakfast', categories: ['Breakfast', 'Quick & Easy', 'Vegetarian'], equipment: STOVE, cookMinutes: 4, cost: 1.40, calories: 350, protein: 10, carbs: 44, fat: 16, ingredients: ['Bread (loaf)', 'Peanut butter', 'Banana'], dietaryTags: ['vegetarian', 'dairy-free'], tips: 'Almond or peanut butter both work — whatever is open.' },
  { id: 'bk-breakfast-quesadilla', name: 'Breakfast Quesadilla', mealType: 'breakfast', categories: ['Breakfast', 'Quick & Easy', 'High Protein'], equipment: STOVE, cookMinutes: 10, cost: 1.90, calories: 430, protein: 22, carbs: 36, fat: 22, ingredients: ['Tortillas', 'Eggs', 'Cheese (shredded)', 'Spinach'], dietaryTags: ['vegetarian', 'nut-free', 'high-protein'], tips: 'Scramble the egg filling first, then fold in a quesadilla.' },
  { id: 'bk-steel-cut-oats', name: 'Steel Cut Oats (Microwave)', mealType: 'breakfast', categories: ['Breakfast', 'Meal Prep', 'Budget Friendly', 'Vegetarian'], equipment: MICRO, cookMinutes: 8, cost: 0.85, calories: 330, protein: 11, carbs: 56, fat: 7, ingredients: ['Oatmeal', 'Milk', 'Banana', 'Peanut butter'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Soak overnight in water to cut cook time by half.' },
  { id: 'bk-waffle-peanut-butter', name: 'Frozen Waffle with PB', mealType: 'breakfast', categories: ['Breakfast', 'College Dorm', 'Quick & Easy', 'Budget Friendly'], equipment: STOVE, cookMinutes: 4, cost: 1.10, calories: 360, protein: 10, carbs: 48, fat: 16, ingredients: ['Peanut butter', 'Banana', 'Butter'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Toast the waffle, spread PB, add sliced banana.' },
  { id: 'bk-turkey-sausage-muffin', name: 'Turkey Egg Muffin', mealType: 'breakfast', categories: ['Breakfast', 'High Protein', 'Quick & Easy'], equipment: STOVE, cookMinutes: 10, cost: 2.20, calories: 380, protein: 28, carbs: 28, fat: 16, ingredients: ['Deli turkey', 'Eggs', 'Cheese (shredded)', 'Bread (loaf)'], dietaryTags: ['nut-free', 'high-protein'], tips: 'Crisp the turkey in the pan for a sausage-like texture.' },
  { id: 'bk-rice-bowl-egg', name: 'Breakfast Rice Bowl', mealType: 'breakfast', categories: ['Breakfast', 'High Protein', 'Quick & Easy'], equipment: MICRO, cookMinutes: 6, cost: 1.40, calories: 420, protein: 16, carbs: 62, fat: 12, ingredients: ['White rice', 'Eggs', 'Soy sauce', 'Hot sauce'], dietaryTags: ['vegetarian', 'dairy-free', 'nut-free'], tips: 'Left-over rice from dinner makes this a 5-minute breakfast.' },
  { id: 'bk-banana-walnut-oatmeal', name: 'Banana Walnut Oatmeal', mealType: 'breakfast', categories: ['Breakfast', 'Budget Friendly', 'Vegetarian', 'Meal Prep'], equipment: MICRO, cookMinutes: 5, cost: 1.00, calories: 400, protein: 12, carbs: 58, fat: 14, ingredients: ['Oatmeal', 'Banana', 'Peanut butter', 'Milk'], dietaryTags: ['vegetarian', 'dairy-free'], tips: 'Add crushed nuts for crunch and extra healthy fats.' },
  { id: 'bk-egg-veggie-bowl', name: 'Egg & Veggie Breakfast Bowl', mealType: 'breakfast', categories: ['Breakfast', 'High Protein', 'Vegetarian', 'Meal Prep'], equipment: STOVE, cookMinutes: 12, cost: 2.00, calories: 360, protein: 20, carbs: 24, fat: 20, ingredients: ['Eggs', 'Spinach', 'Tomato', 'Avocado', 'Olive oil'], dietaryTags: ['vegetarian', 'gluten-free', 'dairy-free', 'nut-free', 'high-protein'], tips: 'Sauté greens, add fried or poached eggs on top.' },
  { id: 'bk-hummus-veggie-toast', name: 'Hummus & Veggie Toast', mealType: 'breakfast', categories: ['Breakfast', 'Vegetarian', 'Quick & Easy'], equipment: ANY, cookMinutes: 4, cost: 1.60, calories: 290, protein: 10, carbs: 38, fat: 12, ingredients: ['Bread (loaf)', 'Canned chickpeas', 'Cucumber', 'Tomato'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'nut-free', 'low-cal'], tips: 'Spread store-bought hummus and pile on raw veggies.' },
  { id: 'bk-microwave-protein-bowl', name: 'Microwave Protein Oat Bowl', mealType: 'breakfast', categories: ['Breakfast', 'High Protein', 'College Dorm', 'Quick & Easy'], equipment: MICRO, cookMinutes: 4, cost: 1.30, calories: 420, protein: 26, carbs: 48, fat: 14, ingredients: ['Oatmeal', 'Milk', 'Greek yogurt', 'Peanut butter', 'Banana'], dietaryTags: ['vegetarian', 'high-protein'], tips: 'Stir Greek yogurt into hot oats — the protein boost is huge.' },
  { id: 'bk-breakfast-grains', name: 'Mixed Grain Porridge', mealType: 'breakfast', categories: ['Breakfast', 'Vegetarian', 'Budget Friendly', 'Meal Prep'], equipment: STOVE, cookMinutes: 15, cost: 0.90, calories: 340, protein: 10, carbs: 60, fat: 8, ingredients: ['Oatmeal', 'White rice', 'Milk', 'Banana'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Cook oats and rice together for a heartier porridge.' },

  /* ════════════════ LUNCH (continued) ════════════════ */
  { id: 'ln-chicken-caesar-salad', name: 'Chicken Caesar Salad', mealType: 'lunch', categories: ['Lunch', 'High Protein', 'Quick & Easy'], equipment: ANY, cookMinutes: 10, cost: 2.40, calories: 420, protein: 36, carbs: 14, fat: 24, ingredients: ['Chicken breast', 'Romaine lettuce', 'Cheese (shredded)', 'Mayonnaise', 'Garlic'], dietaryTags: ['gluten-free', 'nut-free', 'high-protein'], tips: 'Mix mayo with garlic and lemon for an easy dressing.' },
  { id: 'ln-greek-salad', name: 'Greek Salad', mealType: 'lunch', categories: ['Lunch', 'Vegetarian', 'Quick & Easy'], equipment: ANY, cookMinutes: 8, cost: 2.20, calories: 300, protein: 10, carbs: 18, fat: 22, ingredients: ['Cucumber', 'Tomato', 'Onion', 'Cheese (shredded)', 'Olive oil'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free', 'low-cal'], tips: 'Kalamata olives and feta cheese elevate this to the real thing.' },
  { id: 'ln-lentil-soup', name: 'Red Lentil Soup', mealType: 'lunch', categories: ['Lunch', 'Budget Friendly', 'Vegetarian', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 28, cost: 1.40, calories: 360, protein: 20, carbs: 56, fat: 6, ingredients: ['Canned chickpeas', 'Tomato', 'Onion', 'Garlic', 'Spinach'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'high-protein'], tips: 'Red lentils dissolve into the soup — very comforting.' },
  { id: 'ln-sweet-potato-bowl', name: 'Sweet Potato & Black Bean Bowl', mealType: 'lunch', categories: ['Lunch', 'Vegetarian', 'High Protein', 'Budget Friendly'], equipment: MICRO, cookMinutes: 14, cost: 2.00, calories: 440, protein: 16, carbs: 72, fat: 10, ingredients: ['Potato', 'Canned black beans', 'Avocado', 'Spinach', 'Hot sauce'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'nut-free'], tips: 'Microwave the potato, cube it, layer with beans and greens.' },
  { id: 'ln-italian-sub', name: 'Italian Deli Sub', mealType: 'lunch', categories: ['Lunch', 'Quick & Easy', 'High Protein'], equipment: ANY, cookMinutes: 5, cost: 2.20, calories: 520, protein: 28, carbs: 42, fat: 26, ingredients: ['Bread (loaf)', 'Deli turkey', 'Cheese (shredded)', 'Romaine lettuce', 'Tomato', 'Olive oil'], dietaryTags: ['nut-free', 'high-protein'], tips: 'Oil + vinegar on a sub beats mayo every time.' },
  { id: 'ln-mediterranean-bowl', name: 'Mediterranean Grain Bowl', mealType: 'lunch', categories: ['Lunch', 'Vegetarian', 'Meal Prep', 'High Protein'], equipment: STOVE, cookMinutes: 22, cost: 2.60, calories: 460, protein: 18, carbs: 60, fat: 16, ingredients: ['White rice', 'Canned chickpeas', 'Cucumber', 'Tomato', 'Olive oil'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'nut-free'], tips: 'Season with cumin and lemon; top with hot sauce.' },
  { id: 'ln-turkey-meatball-sub', name: 'Turkey Meatball Sub', mealType: 'lunch', categories: ['Lunch', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 22, cost: 2.30, calories: 490, protein: 32, carbs: 44, fat: 20, ingredients: ['Deli turkey', 'Bread (loaf)', 'Tomato', 'Cheese (shredded)', 'Onion'], dietaryTags: ['nut-free', 'high-protein'], tips: 'Form mini turkey patties, pan fry, serve in bread with sauce.' },
  { id: 'ln-pita-hummus-plate', name: 'Pita & Hummus Plate', mealType: 'lunch', categories: ['Lunch', 'Vegetarian', 'Quick & Easy', 'Budget Friendly'], equipment: ANY, cookMinutes: 5, cost: 1.80, calories: 380, protein: 14, carbs: 52, fat: 14, ingredients: ['Tortillas', 'Canned chickpeas', 'Cucumber', 'Tomato', 'Olive oil'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'nut-free'], tips: 'Mash chickpeas into rough hummus or serve whole.' },
  { id: 'ln-cobb-salad', name: 'Cobb Salad', mealType: 'lunch', categories: ['Lunch', 'High Protein'], equipment: STOVE, cookMinutes: 14, cost: 2.60, calories: 460, protein: 34, carbs: 10, fat: 32, ingredients: ['Chicken breast', 'Eggs', 'Romaine lettuce', 'Tomato', 'Avocado'], dietaryTags: ['gluten-free', 'nut-free', 'high-protein'], tips: 'Row each topping for the classic look; dress with olive oil.' },
  { id: 'ln-white-bean-soup', name: 'White Bean & Tomato Soup', mealType: 'lunch', categories: ['Lunch', 'Vegetarian', 'Budget Friendly', 'Meal Prep'], equipment: STOVE, cookMinutes: 22, cost: 1.60, calories: 340, protein: 16, carbs: 52, fat: 8, ingredients: ['Canned chickpeas', 'Tomato', 'Garlic', 'Onion', 'Spinach'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'nut-free', 'low-cal'], tips: 'Simmer 15 min, blend a third for a creamy texture.' },
  { id: 'ln-spicy-tuna-bowl', name: 'Spicy Tuna Rice Bowl', mealType: 'lunch', categories: ['Lunch', 'High Protein', 'Budget Friendly', 'Quick & Easy'], equipment: MICRO, cookMinutes: 8, cost: 2.20, calories: 460, protein: 30, carbs: 56, fat: 12, ingredients: ['Canned tuna', 'White rice', 'Mayonnaise', 'Hot sauce', 'Soy sauce'], dietaryTags: ['dairy-free', 'nut-free', 'high-protein'], tips: 'Mix tuna with mayo and sriracha, spoon over rice.' },
  { id: 'ln-edamame-rice', name: 'Edamame & Brown Rice Bowl', mealType: 'lunch', categories: ['Lunch', 'Vegetarian', 'High Protein', 'Meal Prep'], equipment: MICRO, cookMinutes: 8, cost: 2.00, calories: 420, protein: 20, carbs: 62, fat: 10, ingredients: ['White rice', 'Canned chickpeas', 'Soy sauce', 'Spinach'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Frozen edamame microwaves in 3 min — keep a bag for this.' },
  { id: 'ln-chicken-salad-lettuce', name: 'Chicken Salad Lettuce Cups', mealType: 'lunch', categories: ['Lunch', 'High Protein', 'Quick & Easy'], equipment: ANY, cookMinutes: 8, cost: 2.00, calories: 340, protein: 30, carbs: 10, fat: 20, ingredients: ['Chicken breast', 'Mayonnaise', 'Romaine lettuce', 'Cucumber', 'Black pepper'], dietaryTags: ['gluten-free', 'nut-free', 'high-protein', 'low-cal'], tips: 'Use rotisserie chicken to skip cooking entirely.' },
  { id: 'ln-caprese-sandwich', name: 'Caprese Sandwich', mealType: 'lunch', categories: ['Lunch', 'Vegetarian', 'Quick & Easy'], equipment: ANY, cookMinutes: 5, cost: 1.80, calories: 400, protein: 14, carbs: 38, fat: 22, ingredients: ['Bread (loaf)', 'Tomato', 'Cheese (shredded)', 'Olive oil', 'Spinach'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Thick sliced tomatoes, fresh mozzarella, basil, drizzle of oil.' },
  { id: 'ln-loaded-nachos', name: 'Loaded Nachos', mealType: 'lunch', categories: ['Lunch', 'College Dorm', 'Quick & Easy', 'Vegetarian'], equipment: MICRO, cookMinutes: 6, cost: 2.20, calories: 520, protein: 16, carbs: 56, fat: 26, ingredients: ['Tortillas', 'Canned black beans', 'Cheese (shredded)', 'Hot sauce', 'Avocado'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Break tortillas into chips and microwave with cheese and beans.' },
  { id: 'ln-pasta-e-fagioli', name: 'Pasta & Bean Soup', mealType: 'lunch', categories: ['Lunch', 'Budget Friendly', 'Vegetarian', 'Meal Prep'], equipment: STOVE, cookMinutes: 24, cost: 1.60, calories: 430, protein: 18, carbs: 68, fat: 8, ingredients: ['Pasta', 'Canned chickpeas', 'Tomato', 'Garlic', 'Onion'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'nut-free'], tips: 'Italian pantry soup — pasta and beans in garlicky tomato broth.' },
  { id: 'ln-ham-swiss', name: 'Ham & Cheese Sandwich', mealType: 'lunch', categories: ['Lunch', 'Quick & Easy', 'High Protein'], equipment: ANY, cookMinutes: 4, cost: 2.00, calories: 440, protein: 24, carbs: 36, fat: 20, ingredients: ['Bread (loaf)', 'Deli turkey', 'Cheese (shredded)', 'Mayonnaise', 'Romaine lettuce'], dietaryTags: ['nut-free', 'high-protein'], tips: 'Press it in a pan for a hot grilled version.' },
  { id: 'ln-falafel-wrap', name: 'Chickpea Falafel Wrap', mealType: 'lunch', categories: ['Lunch', 'Vegetarian', 'Budget Friendly', 'High Protein'], equipment: STOVE, cookMinutes: 20, cost: 1.90, calories: 450, protein: 18, carbs: 56, fat: 18, ingredients: ['Canned chickpeas', 'Tortillas', 'Spinach', 'Tomato', 'Onion', 'Olive oil'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'nut-free'], tips: 'Mash chickpeas with garlic and spices, form patties, pan fry.' },
  { id: 'ln-veggie-soba', name: 'Cold Soba Noodle Salad', mealType: 'lunch', categories: ['Lunch', 'Vegetarian', 'Quick & Easy'], equipment: STOVE, cookMinutes: 14, cost: 2.40, calories: 420, protein: 14, carbs: 64, fat: 12, ingredients: ['Pasta', 'Cucumber', 'Soy sauce', 'Peanut butter', 'Spinach'], dietaryTags: ['vegetarian', 'dairy-free'], tips: 'Cook pasta, rinse cold, toss with peanut-soy dressing.' },
  { id: 'ln-stuffed-pepper-lunch', name: 'Stuffed Bell Pepper Cup', mealType: 'lunch', categories: ['Lunch', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 20, cost: 1.80, calories: 380, protein: 22, carbs: 40, fat: 14, ingredients: ['Bell pepper', 'White rice', 'Canned black beans', 'Cheese (shredded)', 'Garlic'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Halve peppers, microwave 4 min, fill with hot rice-bean mix.' },
  { id: 'ln-bean-veggie-soup', name: 'Mixed Bean & Veggie Soup', mealType: 'lunch', categories: ['Lunch', 'Vegetarian', 'Budget Friendly', 'Meal Prep', 'High Protein'], equipment: STOVE, cookMinutes: 25, cost: 1.50, calories: 340, protein: 16, carbs: 52, fat: 6, ingredients: ['Canned black beans', 'Canned chickpeas', 'Frozen vegetables', 'Tomato', 'Garlic'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'nut-free', 'low-cal'], tips: 'Use any two cans of beans and whatever frozen veg is on hand.' },
  { id: 'ln-tuna-avocado-bowl', name: 'Tuna Avocado Bowl', mealType: 'lunch', categories: ['Lunch', 'High Protein', 'Quick & Easy'], equipment: ANY, cookMinutes: 6, cost: 2.00, calories: 420, protein: 28, carbs: 28, fat: 22, ingredients: ['Canned tuna', 'Avocado', 'White rice', 'Soy sauce', 'Cucumber'], dietaryTags: ['dairy-free', 'gluten-free', 'nut-free', 'high-protein'], tips: 'A lazy sushi bowl — no cooking needed if rice is prepped.' },
  { id: 'ln-chicken-soup-box', name: 'Quick Chicken Noodle Soup', mealType: 'lunch', categories: ['Lunch', 'College Dorm', 'Quick & Easy', 'Budget Friendly'], equipment: MICRO, cookMinutes: 8, cost: 1.60, calories: 320, protein: 18, carbs: 36, fat: 8, ingredients: ['Ramen noodles', 'Frozen vegetables', 'Deli turkey', 'Black pepper'], dietaryTags: ['dairy-free', 'nut-free'], tips: 'Make ramen, skip the seasoning, add turkey and veggies.' },
  { id: 'ln-salmon-rice', name: 'Salmon & Rice Bowl', mealType: 'lunch', categories: ['Lunch', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 20, cost: 3.00, calories: 520, protein: 38, carbs: 56, fat: 16, ingredients: ['White rice', 'Cucumber', 'Avocado', 'Soy sauce', 'Olive oil'], dietaryTags: ['dairy-free', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Pan sear salmon in olive oil 4 min per side; serve over rice.' },
  { id: 'ln-veggie-burger', name: 'Black Bean Veggie Burger', mealType: 'lunch', categories: ['Lunch', 'Vegetarian', 'Budget Friendly', 'High Protein'], equipment: STOVE, cookMinutes: 18, cost: 1.80, calories: 420, protein: 18, carbs: 52, fat: 16, ingredients: ['Canned black beans', 'Oatmeal', 'Onion', 'Garlic', 'Bread (loaf)'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'nut-free'], tips: 'Mash beans, mix with oats and spice, pan fry 4 min per side.' },

  /* ════════════════ DINNER (continued) ════════════════ */
  { id: 'dn-lemon-salmon', name: 'Lemon Herb Pan-Seared Salmon', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Quick & Easy'], equipment: STOVE, cookMinutes: 18, cost: 3.20, calories: 480, protein: 44, carbs: 18, fat: 24, ingredients: ['White rice', 'Broccoli', 'Garlic', 'Olive oil', 'Black pepper'], dietaryTags: ['dairy-free', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Season generously with garlic and pepper; skin side down first.' },
  { id: 'dn-beef-broccoli', name: 'Beef & Broccoli Bowl', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Quick & Easy'], equipment: STOVE, cookMinutes: 20, cost: 2.70, calories: 560, protein: 36, carbs: 52, fat: 22, ingredients: ['Ground beef', 'Broccoli', 'White rice', 'Soy sauce', 'Garlic'], dietaryTags: ['dairy-free', 'nut-free', 'high-protein'], tips: 'Stir-fry beef and broccoli with soy; serve over rice.' },
  { id: 'dn-teriyaki-chicken', name: 'Teriyaki Chicken Bowl', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 22, cost: 2.30, calories: 540, protein: 42, carbs: 60, fat: 12, ingredients: ['Chicken breast', 'White rice', 'Soy sauce', 'Garlic', 'Frozen vegetables'], dietaryTags: ['dairy-free', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Soy + garlic + a pinch of sugar = simple teriyaki glaze.' },
  { id: 'dn-pesto-pasta', name: 'Pesto Pasta', mealType: 'dinner', categories: ['Dinner', 'Quick & Easy', 'Vegetarian'], equipment: STOVE, cookMinutes: 18, cost: 2.60, calories: 560, protein: 18, carbs: 74, fat: 22, ingredients: ['Pasta', 'Peanut butter', 'Spinach', 'Garlic', 'Olive oil', 'Cheese (shredded)'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Blend basil, garlic, cheese, and oil — or use store-bought.' },
  { id: 'dn-chicken-fajitas', name: 'Chicken Fajita Bowl', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Quick & Easy'], equipment: STOVE, cookMinutes: 20, cost: 2.40, calories: 520, protein: 38, carbs: 46, fat: 18, ingredients: ['Chicken breast', 'Bell pepper', 'Onion', 'Tortillas', 'Cheese (shredded)'], dietaryTags: ['nut-free', 'high-protein'], tips: 'Slice chicken thin and cook hot so it chars a little.' },
  { id: 'dn-lentil-dal', name: 'Red Lentil Dal & Rice', mealType: 'dinner', categories: ['Dinner', 'Vegetarian', 'Budget Friendly', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 25, cost: 1.80, calories: 500, protein: 22, carbs: 82, fat: 8, ingredients: ['Canned chickpeas', 'White rice', 'Tomato', 'Onion', 'Garlic', 'Spinach'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Cumin, turmeric, and coriander transform chickpeas completely.' },
  { id: 'dn-shrimp-tacos', name: 'Shrimp Tacos', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Quick & Easy'], equipment: STOVE, cookMinutes: 16, cost: 2.80, calories: 480, protein: 30, carbs: 44, fat: 18, ingredients: ['Tortillas', 'Frozen vegetables', 'Avocado', 'Soy sauce', 'Lime'], dietaryTags: ['dairy-free', 'nut-free', 'high-protein'], tips: 'Frozen shrimp thaws in cold water in 10 min — very convenient.' },
  { id: 'dn-turkey-taco-bowl', name: 'Ground Turkey Taco Bowl', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Meal Prep', 'Budget Friendly'], equipment: STOVE, cookMinutes: 22, cost: 2.80, calories: 520, protein: 36, carbs: 52, fat: 18, ingredients: ['Deli turkey', 'White rice', 'Canned black beans', 'Cheese (shredded)', 'Hot sauce'], dietaryTags: ['gluten-free', 'nut-free', 'high-protein'], tips: 'Ground turkey is leaner and cheaper than ground beef.' },
  { id: 'dn-bbq-chicken-bowl', name: 'BBQ Chicken Rice Bowl', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 25, cost: 2.30, calories: 560, protein: 40, carbs: 60, fat: 14, ingredients: ['Chicken breast', 'White rice', 'Broccoli', 'Hot sauce', 'Garlic'], dietaryTags: ['dairy-free', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Mix hot sauce + a little butter as a lazy BBQ sauce.' },
  { id: 'dn-honey-garlic-chicken', name: 'Honey Garlic Chicken', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Quick & Easy', 'Meal Prep'], equipment: STOVE, cookMinutes: 20, cost: 2.40, calories: 520, protein: 40, carbs: 46, fat: 16, ingredients: ['Chicken breast', 'Garlic', 'Soy sauce', 'White rice', 'Broccoli'], dietaryTags: ['dairy-free', 'nut-free', 'high-protein'], tips: 'Soy + garlic + a little sugar + butter makes the best glaze.' },
  { id: 'dn-stuffed-peppers', name: 'Stuffed Bell Peppers', mealType: 'dinner', categories: ['Dinner', 'Meal Prep', 'High Protein'], equipment: STOVE, cookMinutes: 35, cost: 2.50, calories: 480, protein: 28, carbs: 52, fat: 18, ingredients: ['Bell pepper', 'Ground beef', 'White rice', 'Tomato', 'Cheese (shredded)'], dietaryTags: ['gluten-free', 'nut-free', 'high-protein'], tips: 'Halve peppers, fill with beef-rice mix, bake at 375°F for 25 min.' },
  { id: 'dn-sesame-noodles', name: 'Sesame Peanut Noodles', mealType: 'dinner', categories: ['Dinner', 'Quick & Easy', 'Budget Friendly', 'Vegetarian'], equipment: STOVE, cookMinutes: 14, cost: 1.80, calories: 520, protein: 16, carbs: 72, fat: 20, ingredients: ['Pasta', 'Peanut butter', 'Soy sauce', 'Garlic', 'Cucumber'], dietaryTags: ['vegetarian', 'dairy-free'], tips: 'Whisk peanut butter, soy, garlic into a smooth sauce; toss with pasta.' },
  { id: 'dn-white-bean-stew', name: 'White Bean & Spinach Stew', mealType: 'dinner', categories: ['Dinner', 'Vegetarian', 'Budget Friendly', 'Meal Prep', 'High Protein'], equipment: STOVE, cookMinutes: 22, cost: 1.70, calories: 380, protein: 18, carbs: 56, fat: 8, ingredients: ['Canned chickpeas', 'Spinach', 'Tomato', 'Garlic', 'Onion', 'Olive oil'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'nut-free', 'high-protein'], tips: 'A full meal in one pot — very cheap per serving.' },
  { id: 'dn-turkey-burger', name: 'Turkey Burger & Fries', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Quick & Easy'], equipment: STOVE, cookMinutes: 22, cost: 2.20, calories: 540, protein: 32, carbs: 46, fat: 22, ingredients: ['Deli turkey', 'Bread (loaf)', 'Onion', 'Tomato', 'Potato'], dietaryTags: ['nut-free', 'high-protein'], tips: 'Mix ground turkey with garlic and salt; cook baked potato wedge fries.' },
  { id: 'dn-cheesy-beef-rice', name: 'Cheesy Ground Beef & Rice', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Budget Friendly', 'Quick & Easy'], equipment: STOVE, cookMinutes: 22, cost: 2.60, calories: 580, protein: 34, carbs: 52, fat: 24, ingredients: ['Ground beef', 'White rice', 'Cheese (shredded)', 'Onion', 'Garlic'], dietaryTags: ['gluten-free', 'nut-free', 'high-protein'], tips: 'Brown beef with onion, stir in cooked rice, top with cheese.' },
  { id: 'dn-salmon-patties', name: 'Canned Salmon Patties', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Budget Friendly'], equipment: STOVE, cookMinutes: 18, cost: 2.80, calories: 420, protein: 34, carbs: 24, fat: 20, ingredients: ['Canned tuna', 'Eggs', 'Oatmeal', 'Onion', 'Black pepper'], dietaryTags: ['dairy-free', 'nut-free', 'high-protein'], tips: 'Canned tuna or salmon, bound with egg and oats, pan-fried.' },
  { id: 'dn-spicy-sausage-pasta', name: 'Spicy Sausage Pasta', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Quick & Easy', 'Meal Prep'], equipment: STOVE, cookMinutes: 22, cost: 2.40, calories: 620, protein: 30, carbs: 68, fat: 26, ingredients: ['Pasta', 'Ground beef', 'Tomato', 'Garlic', 'Hot sauce', 'Cheese (shredded)'], dietaryTags: ['nut-free', 'high-protein'], tips: 'Brown beef with red pepper flakes; toss with pasta and tomato sauce.' },
  { id: 'dn-tuna-noodle', name: 'Tuna Noodle Casserole', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Budget Friendly', 'Meal Prep'], equipment: STOVE, cookMinutes: 24, cost: 2.20, calories: 520, protein: 30, carbs: 60, fat: 16, ingredients: ['Pasta', 'Canned tuna', 'Milk', 'Cheese (shredded)', 'Frozen vegetables'], dietaryTags: ['nut-free', 'high-protein'], tips: 'A classic comfort dish made with pantry staples.' },
  { id: 'dn-pita-pizza', name: 'Pita Pizza', mealType: 'dinner', categories: ['Dinner', 'Quick & Easy', 'Vegetarian', 'Budget Friendly'], equipment: STOVE, cookMinutes: 14, cost: 1.90, calories: 440, protein: 16, carbs: 52, fat: 18, ingredients: ['Tortillas', 'Tomato', 'Cheese (shredded)', 'Garlic', 'Spinach'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Tortilla crisps up like thin-crust pizza in a pan or oven.' },
  { id: 'dn-spinach-ricotta-pasta', name: 'Spinach & Cream Cheese Pasta', mealType: 'dinner', categories: ['Dinner', 'Vegetarian', 'Quick & Easy', 'Meal Prep'], equipment: STOVE, cookMinutes: 18, cost: 2.40, calories: 540, protein: 18, carbs: 72, fat: 20, ingredients: ['Pasta', 'Cream cheese', 'Spinach', 'Garlic', 'Black pepper'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Melt cream cheese into pasta water; spinach wilts in 2 min.' },
  { id: 'dn-chicken-noodle-soup', name: 'Chicken Noodle Soup', mealType: 'dinner', categories: ['Dinner', 'Meal Prep', 'High Protein', 'Budget Friendly'], equipment: STOVE, cookMinutes: 30, cost: 2.60, calories: 400, protein: 28, carbs: 42, fat: 10, ingredients: ['Chicken breast', 'Pasta', 'Carrot', 'Onion', 'Garlic', 'Black pepper'], dietaryTags: ['dairy-free', 'nut-free', 'high-protein'], tips: 'Use any vegetables you have; simmer 20 min for depth of flavor.' },
  { id: 'dn-veg-lentil-soup', name: 'Vegetarian Lentil Soup', mealType: 'dinner', categories: ['Dinner', 'Vegetarian', 'Budget Friendly', 'Meal Prep', 'High Protein'], equipment: STOVE, cookMinutes: 28, cost: 1.60, calories: 380, protein: 20, carbs: 60, fat: 6, ingredients: ['Canned chickpeas', 'Tomato', 'Carrot', 'Onion', 'Garlic', 'Spinach'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'nut-free', 'high-protein', 'low-cal'], tips: 'Simmer longer for a smoother, thicker consistency.' },
  { id: 'dn-baked-cod', name: 'Baked Cod & Vegetables', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Quick & Easy'], equipment: STOVE, cookMinutes: 22, cost: 2.80, calories: 380, protein: 40, carbs: 24, fat: 12, ingredients: ['Frozen vegetables', 'Olive oil', 'Garlic', 'Black pepper', 'White rice'], dietaryTags: ['dairy-free', 'gluten-free', 'nut-free', 'high-protein', 'low-cal'], tips: 'Any white fish bakes at 400°F for 12–14 min — simple and lean.' },
  { id: 'dn-pork-chop', name: 'Pan-Seared Pork Chop & Potato', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Quick & Easy'], equipment: STOVE, cookMinutes: 24, cost: 2.50, calories: 560, protein: 38, carbs: 36, fat: 26, ingredients: ['Potato', 'Onion', 'Garlic', 'Olive oil', 'Black pepper'], dietaryTags: ['dairy-free', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Pork chops cook in 4–5 min per side on medium-high heat.' },
  { id: 'dn-soy-glazed-chicken', name: 'Soy Glazed Chicken Thighs', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Budget Friendly', 'Meal Prep'], equipment: STOVE, cookMinutes: 25, cost: 2.00, calories: 500, protein: 36, carbs: 36, fat: 22, ingredients: ['Chicken breast', 'Soy sauce', 'Garlic', 'White rice', 'Broccoli'], dietaryTags: ['dairy-free', 'nut-free', 'high-protein'], tips: 'Chicken thighs are cheaper and more forgiving than breasts.' },
  { id: 'dn-beef-bean-burrito', name: 'Beef & Bean Burrito', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Budget Friendly'], equipment: STOVE, cookMinutes: 20, cost: 2.80, calories: 620, protein: 32, carbs: 66, fat: 26, ingredients: ['Ground beef', 'Canned black beans', 'Tortillas', 'Cheese (shredded)', 'Hot sauce'], dietaryTags: ['nut-free', 'high-protein'], tips: 'Wrap tight and sear seam-side down for a crispy burrito.' },
  { id: 'dn-chickpea-spinach-stew', name: 'Chickpea Spinach Stew', mealType: 'dinner', categories: ['Dinner', 'Vegetarian', 'High Protein', 'Budget Friendly', 'Meal Prep'], equipment: STOVE, cookMinutes: 22, cost: 1.90, calories: 400, protein: 18, carbs: 56, fat: 10, ingredients: ['Canned chickpeas', 'Spinach', 'Tomato', 'Onion', 'Garlic', 'Olive oil'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Add a squeeze of lemon at the end — it brightens the entire dish.' },
  { id: 'dn-ground-turkey-bowl', name: 'Ground Turkey Veggie Bowl', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Meal Prep', 'Budget Friendly'], equipment: STOVE, cookMinutes: 22, cost: 2.70, calories: 510, protein: 40, carbs: 42, fat: 18, ingredients: ['Deli turkey', 'White rice', 'Frozen vegetables', 'Soy sauce', 'Garlic'], dietaryTags: ['dairy-free', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Ground turkey is one of the best protein values per dollar.' },
  { id: 'dn-chicken-fried-quinoa', name: 'Chicken Fried Quinoa', mealType: 'dinner', categories: ['Dinner', 'High Protein', 'Meal Prep'], equipment: STOVE, cookMinutes: 25, cost: 2.40, calories: 490, protein: 38, carbs: 48, fat: 14, ingredients: ['Chicken breast', 'White rice', 'Eggs', 'Frozen vegetables', 'Soy sauce'], dietaryTags: ['dairy-free', 'gluten-free', 'nut-free', 'high-protein'], tips: 'Use white rice or quinoa — both work great stir-fried.' },

  /* ════════════════ SNACKS ════════════════ */
  { id: 'sn-trail-mix', name: 'Trail Mix', mealType: 'breakfast', categories: ['Snacks', 'Quick & Easy', 'Budget Friendly', 'Vegetarian', 'High Protein'], equipment: ANY, cookMinutes: 2, cost: 0.80, calories: 260, protein: 8, carbs: 26, fat: 16, ingredients: ['Peanut butter', 'Granola bar', 'Oatmeal'], dietaryTags: ['vegetarian', 'dairy-free', 'gluten-free'], tips: 'Mix nuts, dried fruit, and a few chocolate chips.' },
  { id: 'sn-rice-cakes-pb', name: 'Rice Cakes with Peanut Butter', mealType: 'breakfast', categories: ['Snacks', 'Quick & Easy', 'Budget Friendly', 'Vegetarian', 'High Protein'], equipment: ANY, cookMinutes: 2, cost: 0.90, calories: 220, protein: 8, carbs: 28, fat: 10, ingredients: ['Peanut butter', 'Banana'], dietaryTags: ['vegetarian', 'dairy-free', 'gluten-free', 'vegan'], tips: 'Spread peanut butter on rice cakes; add banana for sweetness.' },
  { id: 'sn-cheese-apple', name: 'Apple Slices & Cheese', mealType: 'breakfast', categories: ['Snacks', 'Quick & Easy', 'Vegetarian'], equipment: ANY, cookMinutes: 3, cost: 1.20, calories: 200, protein: 8, carbs: 24, fat: 8, ingredients: ['Apple', 'Cheese (shredded)'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free'], tips: 'String cheese or a cheese slice pairs perfectly with apple.' },
  { id: 'sn-hummus-veggies', name: 'Hummus & Veggie Dippers', mealType: 'breakfast', categories: ['Snacks', 'Quick & Easy', 'Vegetarian', 'Budget Friendly'], equipment: ANY, cookMinutes: 5, cost: 1.40, calories: 180, protein: 8, carbs: 22, fat: 8, ingredients: ['Canned chickpeas', 'Cucumber', 'Bell pepper', 'Carrot', 'Olive oil'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'nut-free', 'low-cal'], tips: 'Quick hummus: blend chickpeas, olive oil, garlic, salt.' },
  { id: 'sn-hardboiled-egg', name: 'Hard-Boiled Eggs', mealType: 'breakfast', categories: ['Snacks', 'High Protein', 'Meal Prep', 'Budget Friendly'], equipment: STOVE, cookMinutes: 14, cost: 0.50, calories: 140, protein: 12, carbs: 1, fat: 9, ingredients: ['Eggs', 'Salt'], dietaryTags: ['vegetarian', 'gluten-free', 'dairy-free', 'nut-free', 'high-protein', 'low-cal'], tips: 'Boil 6 at once; refrigerate unpeeled up to 1 week.' },
  { id: 'sn-greek-yogurt-plain', name: 'Greek Yogurt Cup', mealType: 'breakfast', categories: ['Snacks', 'High Protein', 'Quick & Easy', 'Vegetarian'], equipment: ANY, cookMinutes: 1, cost: 1.20, calories: 180, protein: 18, carbs: 14, fat: 4, ingredients: ['Greek yogurt', 'Banana'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free', 'high-protein', 'low-cal'], tips: 'Plain Greek yogurt with a drizzle of honey is a perfect macro snack.' },
  { id: 'sn-pb-celery', name: 'Peanut Butter & Celery', mealType: 'breakfast', categories: ['Snacks', 'Quick & Easy', 'Budget Friendly', 'Vegetarian'], equipment: ANY, cookMinutes: 2, cost: 0.70, calories: 170, protein: 6, carbs: 10, fat: 13, ingredients: ['Peanut butter', 'Cucumber'], dietaryTags: ['vegetarian', 'dairy-free', 'gluten-free', 'vegan'], tips: 'Classic "ants on a log" — cheap, filling, satisfying crunch.' },
  { id: 'sn-mixed-nuts', name: 'Mixed Nuts', mealType: 'breakfast', categories: ['Snacks', 'Quick & Easy', 'Vegetarian', 'High Protein'], equipment: ANY, cookMinutes: 1, cost: 0.90, calories: 200, protein: 6, carbs: 8, fat: 18, ingredients: ['Peanut butter'], dietaryTags: ['vegetarian', 'dairy-free', 'gluten-free', 'vegan'], tips: 'A small handful (28g) is the right portion; easy to overeat.' },
  { id: 'sn-cheese-crackers', name: 'Cheese & Crackers', mealType: 'breakfast', categories: ['Snacks', 'Quick & Easy', 'Budget Friendly', 'Vegetarian'], equipment: ANY, cookMinutes: 2, cost: 1.00, calories: 240, protein: 8, carbs: 26, fat: 12, ingredients: ['Cheese (shredded)', 'Tomato'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Use any firm crackers you have; pair with any cheese.' },
  { id: 'sn-cottage-fruit', name: 'Cottage Cheese with Fruit', mealType: 'breakfast', categories: ['Snacks', 'High Protein', 'Vegetarian', 'Quick & Easy'], equipment: ANY, cookMinutes: 2, cost: 1.40, calories: 200, protein: 20, carbs: 16, fat: 5, ingredients: ['Cottage cheese', 'Banana'], dietaryTags: ['vegetarian', 'gluten-free', 'nut-free', 'high-protein', 'low-cal'], tips: 'One of the best protein-to-calorie ratios of any snack.' },
  { id: 'sn-banana-almond', name: 'Banana & Nut Butter', mealType: 'breakfast', categories: ['Snacks', 'Quick & Easy', 'Budget Friendly', 'Vegetarian'], equipment: ANY, cookMinutes: 1, cost: 0.90, calories: 260, protein: 6, carbs: 38, fat: 12, ingredients: ['Banana', 'Peanut butter'], dietaryTags: ['vegetarian', 'dairy-free', 'gluten-free', 'vegan'], tips: 'Eat it whole or slice it for easier dipping.' },
  { id: 'sn-protein-oat-ball', name: 'No-Bake Oat Protein Ball', mealType: 'breakfast', categories: ['Snacks', 'High Protein', 'Meal Prep', 'Vegetarian', 'Budget Friendly'], equipment: FRIDGE, cookMinutes: 10, cost: 0.60, calories: 220, protein: 10, carbs: 28, fat: 10, ingredients: ['Oatmeal', 'Peanut butter', 'Banana'], dietaryTags: ['vegetarian', 'dairy-free', 'gluten-free', 'vegan', 'high-protein'], tips: 'Mix oats, peanut butter, and honey; roll into balls, chill 30 min.' },
  { id: 'sn-edamame', name: 'Steamed Edamame', mealType: 'breakfast', categories: ['Snacks', 'High Protein', 'Quick & Easy', 'Vegetarian'], equipment: MICRO, cookMinutes: 4, cost: 1.00, calories: 160, protein: 14, carbs: 14, fat: 6, ingredients: ['Canned chickpeas', 'Salt'], dietaryTags: ['vegetarian', 'vegan', 'dairy-free', 'gluten-free', 'nut-free', 'high-protein', 'low-cal'], tips: 'Frozen edamame: microwave 3 min, add salt, shell as you eat.' },
  { id: 'sn-pita-tzatziki', name: 'Pita & Yogurt Dip', mealType: 'breakfast', categories: ['Snacks', 'Quick & Easy', 'Vegetarian', 'High Protein'], equipment: ANY, cookMinutes: 4, cost: 1.30, calories: 240, protein: 12, carbs: 30, fat: 8, ingredients: ['Tortillas', 'Greek yogurt', 'Cucumber', 'Garlic'], dietaryTags: ['vegetarian', 'nut-free', 'high-protein'], tips: 'Mix yogurt with garlic and cucumber for a fast tzatziki.' },
  { id: 'sn-granola-milk', name: 'Granola & Milk', mealType: 'breakfast', categories: ['Snacks', 'Quick & Easy', 'Budget Friendly', 'Vegetarian'], equipment: ANY, cookMinutes: 2, cost: 1.00, calories: 280, protein: 8, carbs: 46, fat: 8, ingredients: ['Granola bar', 'Milk'], dietaryTags: ['vegetarian', 'nut-free'], tips: 'Crush a granola bar into milk — a quick, satisfying snack.' },
]

/* ════════════════════════════════════════════════════════════════
   DERIVED INDEXES & HELPERS
   ════════════════════════════════════════════════════════════════ */

/** Recipes grouped by meal type (for the generator pools). */
export const RECIPES_BY_MEAL: Record<MealTypeKey, LibraryRecipe[]> = {
  breakfast: RECIPE_LIBRARY.filter(r => r.mealType === 'breakfast'),
  lunch:     RECIPE_LIBRARY.filter(r => r.mealType === 'lunch'),
  dinner:    RECIPE_LIBRARY.filter(r => r.mealType === 'dinner'),
}

/** Count of recipes that list a given category (for badge display). */
export function recipeCountForCategory(category: string): number {
  if (category === 'All') return RECIPE_LIBRARY.length
  return RECIPE_LIBRARY.filter(r => r.categories.includes(category)).length
}

/**
 * Filter the library by category, free-text query, equipment, dietary tags,
 * disliked ingredients, and hidden recipe IDs. All filters are AND-combined.
 */
export function filterLibrary(opts: {
  category?:  string
  query?:     string
  equipment?: EquipmentTier[]
  dietary?:   string[]
  disliked?:  string[]
  hiddenIds?: Set<string>
}): LibraryRecipe[] {
  const { category = 'All', query = '', equipment = [], dietary = [], disliked = [], hiddenIds } = opts
  const q     = query.trim().toLowerCase()
  const lower = disliked.map(d => d.toLowerCase())

  return RECIPE_LIBRARY.filter(r => {
    if (hiddenIds && hiddenIds.has(r.id)) return false
    if (category !== 'All' && !r.categories.includes(category)) return false
    if (q) {
      const hay = `${r.name} ${r.ingredients.join(' ')} ${r.categories.join(' ')}`.toLowerCase()
      if (!hay.includes(q)) return false
    }
    if (equipment.length && !equipment.some(e => r.equipment.includes(e))) return false
    if (dietary.length  && !dietary.every(tag => r.dietaryTags.includes(tag))) return false
    if (lower.length) {
      const hasDisliked = r.ingredients.some(ing => lower.some(d => ing.toLowerCase().includes(d)))
      if (hasDisliked) return false
    }
    return true
  })
}
